mod ast;
mod diag;
mod lexer;
mod parser;
mod pipeline;
mod typecheck;
mod typed;

pub use ast::{parse_toplevel, Expr, FnDef, StructDef, Top, Ty};
pub use diag::{render_diag, Diag, DslResult, Loc, Span};
pub use lexer::{lex, Tok, TokKind};
pub use pipeline::{analyze, PipelineOutput};
pub use parser::{Parser, Sexp};
pub use typecheck::{typecheck_fn, typecheck_tops, TypeEnv, TypecheckedProgram};
pub use typed::{CastHint, TypedExpr, TypedFn};


fn lower(pipeline: &PipelineOutput) -> DslResult<String> {
    let mut out = String::new();
    out.push_str("// Generated by dslc (MVP)\n");
    out.push_str("#![allow(dead_code)]\n\n");

    for t in &pipeline.tops {
        if let Top::Struct(sd) = t {
            out.push_str(&format!("pub struct {} {{\n", sd.name));
            for f in &sd.fields {
                out.push_str(&format!("    pub {}: {},\n", f.name, f.ty.rust()));
            }
            out.push_str("}\n\n");
        }
    }

    let mut typed_iter = pipeline.typechecked.typed_fns.iter();
    for t in &pipeline.tops {
        if let Top::Func(fd) = t {
            let typed = typed_iter.next().ok_or_else(|| {
                Diag::new("internal error: missing typed function").with_span(fd.span.clone())
            })?;
            if typed.def.name != fd.name {
                return Err(Diag::new("internal error: typed function order mismatch")
                    .with_span(fd.span.clone()));
            }
            out.push_str(&format!("pub fn {}(", fd.name));
            let mut first = true;
            for p in &fd.params {
                if !first {
                    out.push_str(", ");
                }
                first = false;
                let ty = typed.param_tys.get(&p.name).ok_or_else(|| {
                    Diag::new("internal error: missing param type").with_span(p.span.clone())
                })?;
                out.push_str(&format!("{}: {}", p.name, ty.rust()));
            }
            out.push_str(&format!(") -> {} {{\n", typed.body.ty.rust()));
            out.push_str("    ");
            out.push_str(&lower_expr(&fd.body, &typed.body.casts));
            out.push_str("\n}\n\n");
        }
    }

    Ok(out)
}

fn lower_expr(e: &Expr, casts: &[CastHint]) -> String {
    let mut inner = match e {
        Expr::Int(v, _) => v.to_string(),
        Expr::Float(v, _) => {
            let mut s = v.to_string();
            if !s.contains('.') && !s.contains('e') && !s.contains('E') {
                s.push_str(".0");
            }
            s
        }
        Expr::Var(v, _) => v.clone(),
        Expr::Field { base, field, .. } => format!("{}.{}", lower_expr(base, casts), field),
        Expr::Call { op, args, .. } => {
            if args.len() == 2 && ["+", "-", "*", "/"].contains(&op.as_str()) {
                format!(
                    "({} {} {})",
                    lower_expr(&args[0], casts),
                    op,
                    lower_expr(&args[1], casts)
                )
            } else {
                format!("/* unsupported call {} */", op)
            }
        }
    };

    for ch in casts {
        if spans_eq(&e.span(), &ch.span) {
            inner = format!("({} as {})", inner, ch.target.rust());
            break;
        }
    }
    inner
}

fn spans_eq(a: &Span, b: &Span) -> bool {
    a.start.byte == b.start.byte && a.end.byte == b.end.byte
}

pub fn compile(src: &str) -> DslResult<String> {
    let pipeline = analyze(src)?;
    lower(&pipeline)
}
