use std::collections::BTreeMap;

use crate::ast::{Expr, MatchPat, StructDef, Top, Ty, VariantDef};
use crate::diag::{Diag, DslResult, Span};
use crate::typed::{SpanKey, TypedFn};
use crate::PipelineOutput;

pub fn lower_program(pipeline: &PipelineOutput) -> DslResult<String> {
    let mut out = String::new();
    out.push_str("// Generated by dslc (MVP)\n");
    out.push_str("#![allow(dead_code)]\n\n");

    let mut structs = BTreeMap::new();
    let mut unions = BTreeMap::new();
    let mut variants: BTreeMap<String, (String, VariantDef)> = BTreeMap::new();
    for t in &pipeline.tops {
        if let Top::Struct(sd) = t {
            structs.insert(sd.name.clone(), sd.clone());
            out.push_str(&format!("#[derive(Debug, Clone)]\n"));
            out.push_str(&format!("pub struct {} {{\n", sd.name));
            for f in &sd.fields {
                out.push_str(&format!("    pub {}: {},\n", f.name, f.ty.rust()));
            }
            out.push_str("}\n\n");
        }
        if let Top::Union(ud) = t {
            unions.insert(ud.name.clone(), ud.clone());
            for v in &ud.variants {
                variants.insert(v.name.clone(), (ud.name.clone(), v.clone()));
            }
        }
    }

    for ud in unions.values() {
        out.push_str(&format!("#[derive(Debug, Clone)]\n"));
        out.push_str(&format!("pub enum {} {{\n", ud.name));
        for v in &ud.variants {
            if v.fields.is_empty() {
                out.push_str(&format!("    {},\n", v.name));
            } else {
                out.push_str(&format!("    {} {{\n", v.name));
                for f in &v.fields {
                    out.push_str(&format!("        {}: {},\n", f.name, f.ty.rust()));
                }
                out.push_str("    },\n");
            }
        }
        out.push_str("}\n\n");
    }

    let mut typed_iter = pipeline.typechecked.typed_fns.iter();
    for t in &pipeline.tops {
        if let Top::Func(fd) = t {
            let typed = typed_iter.next().ok_or_else(|| {
                Diag::new("internal error: missing typed function").with_span(fd.span.clone())
            })?;
            if typed.def.name != fd.name {
                return Err(Diag::new("internal error: typed function order mismatch")
                    .with_span(fd.span.clone()));
            }
            let is_main = fd.name == "main" && fd.params.is_empty();
            out.push_str(&format!("pub fn {}(", fd.name));
            emit_params(&mut out, fd, typed)?;
            if is_main {
                out.push_str(") {\n");
            } else {
                out.push_str(&format!(") -> {} {{\n", typed.body.ty.rust()));
            }
            out.push_str("    ");
            out.push_str(&lower_expr(
                &fd.body,
                &typed.body.casts,
                &typed.body.types,
                &structs,
                &variants,
            ));
            if is_main {
                out.push_str(";\n}\n\n");
            } else {
                out.push_str("\n}\n\n");
            }
        }
    }

    Ok(out)
}

fn emit_params(out: &mut String, fd: &crate::ast::FnDef, typed: &TypedFn) -> DslResult<()> {
    let mut first = true;
    for p in &fd.params {
        if !first {
            out.push_str(", ");
        }
        first = false;
        let ty = typed.param_tys.get(&p.name).ok_or_else(|| {
            Diag::new("internal error: missing param type").with_span(p.span.clone())
        })?;
        out.push_str(&format!("{}: {}", p.name, ty.rust()));
    }
    Ok(())
}

fn lower_expr(
    e: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
) -> String {
    let mut inner = match e {
        Expr::Int(v, _) => v.to_string(),
        Expr::Float(v, _) => {
            let mut s = v.to_string();
            if !s.contains('.') && !s.contains('e') && !s.contains('E') {
                s.push_str(".0");
            }
            s
        }
        Expr::Var(v, _) => v.clone(),
        Expr::VecLit { elems, ann, .. } => {
            if elems.is_empty() {
                if let Some(Ty::Vec(inner)) = ann {
                    format!("Vec::<{}>::new()", inner.rust())
                } else {
                    "vec![]".to_string()
                }
            } else {
                let rendered: Vec<String> = elems
                    .iter()
                    .map(|el| lower_expr(el, casts, types, structs, variants))
                    .collect();
                format!("vec![{}]", rendered.join(", "))
            }
        }
        Expr::Field { base, field, span: _ } => {
            let base_ty = expr_ty(types, &base.span());
            if let Some(Ty::Vec(_)) = base_ty {
                let base_expr = lower_expr(base, casts, types, structs, variants);
                format!(
                    "({}).into_iter().map(|__x| __x.{}).collect::<Vec<_>>()",
                    base_expr, field
                )
            } else {
                format!("{}.{}", lower_expr(base, casts, types, structs, variants), field)
            }
        }
        Expr::Match { scrutinee, arms, .. } => {
            let scrut = lower_expr(scrutinee, casts, types, structs, variants);
            let mut rendered = String::new();
            rendered.push_str(&format!("match {} {{ ", scrut));
            for arm in arms {
                match &arm.pat {
                    MatchPat::Wildcard(_) => {
                        rendered.push_str("_ => ");
                    }
                    MatchPat::Variant { name, bindings, .. } => {
                        if let Some((union_name, vdef)) = variants.get(name) {
                            if vdef.fields.is_empty() {
                                rendered.push_str(&format!("{}::{} => ", union_name, name));
                            } else {
                                let mut parts = Vec::new();
                                for (field, binding, _) in bindings {
                                    if binding == "_" {
                                        parts.push(format!("{}: _", field));
                                    } else {
                                        parts.push(format!("{}: {}", field, binding));
                                    }
                                }
                                rendered.push_str(&format!(
                                    "{}::{} {{ {} }} => ",
                                    union_name,
                                    name,
                                    parts.join(", ")
                                ));
                            }
                        } else {
                            rendered.push_str(&format!("{} => ", name));
                        }
                    }
                }
                let body = lower_expr(&arm.body, casts, types, structs, variants);
                rendered.push_str(&format!("{}, ", body));
            }
            rendered.push_str("}");
            rendered
        }
        Expr::Call { op, args, span: _ } => {
            if op == "print" && args.len() == 1 {
                return format!(
                    "println!(\"{{:?}}\", {})",
                    lower_expr(&args[0], casts, types, structs, variants)
                );
            }
            if let Some(sd) = structs.get(op) {
                let rendered: Vec<String> = args
                    .iter()
                    .map(|el| lower_expr(el, casts, types, structs, variants))
                    .collect();
                let mut parts = Vec::new();
                for (field, expr) in sd.fields.iter().zip(rendered.iter()) {
                    parts.push(format!("{}: {}", field.name, expr));
                }
                return format!("{} {{ {} }}", op, parts.join(", "));
            }
            if let Some((union_name, vdef)) = variants.get(op) {
                let rendered: Vec<String> = args
                    .iter()
                    .map(|el| lower_expr(el, casts, types, structs, variants))
                    .collect();
                let mut parts = Vec::new();
                for (field, expr) in vdef.fields.iter().zip(rendered.iter()) {
                    parts.push(format!("{}: {}", field.name, expr));
                }
                return if vdef.fields.is_empty() {
                    format!("{}::{}", union_name, op)
                } else {
                    format!("{}::{} {{ {} }}", union_name, op, parts.join(", "))
                };
            }
            if args.len() == 2 && ["+", "-", "*", "/"].contains(&op.as_str()) {
                let left_ty = expr_ty(types, &args[0].span());
                let right_ty = expr_ty(types, &args[1].span());
                if let (Some(Ty::Vec(_)), Some(right_ty)) = (left_ty.clone(), right_ty.clone()) {
                    return vec_scalar_binop(
                        op,
                        &args[0],
                        &args[1],
                        casts,
                        types,
                        structs,
                        variants,
                        true,
                        &right_ty,
                    );
                }
                if let (Some(left_ty), Some(Ty::Vec(_))) = (left_ty.clone(), right_ty.clone()) {
                    return vec_scalar_binop(
                        op,
                        &args[0],
                        &args[1],
                        casts,
                        types,
                        structs,
                        variants,
                        false,
                        &left_ty,
                    );
                }
                format!(
                    "({} {} {})",
                    lower_expr(&args[0], casts, types, structs, variants),
                    op,
                    lower_expr(&args[1], casts, types, structs, variants)
                )
            } else {
                let rendered: Vec<String> = args
                    .iter()
                    .map(|el| lower_expr(el, casts, types, structs, variants))
                    .collect();
                format!("{}({})", op, rendered.join(", "))
            }
        }
    };

    for ch in casts {
        if spans_eq(&e.span(), &ch.span) {
            inner = format!("({} as {})", inner, ch.target.rust());
            break;
        }
    }
    inner
}

fn spans_eq(a: &Span, b: &Span) -> bool {
    a.start.byte == b.start.byte && a.end.byte == b.end.byte
}

fn expr_ty(types: &BTreeMap<SpanKey, Ty>, span: &Span) -> Option<Ty> {
    types.get(&SpanKey::new(span)).cloned()
}

fn vec_scalar_binop(
    op: &str,
    left: &Expr,
    right: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    vec_on_left: bool,
    scalar_ty: &Ty,
) -> String {
    let vec_expr = if vec_on_left { left } else { right };
    let scalar_expr = if vec_on_left { right } else { left };
    let vec_render = lower_expr(vec_expr, casts, types, structs, variants);
    let scalar_render = lower_expr(scalar_expr, casts, types, structs, variants);
    let scalar = match scalar_ty {
        Ty::Named(_) => scalar_render,
        _ => scalar_render,
    };
    format!(
        "({}).into_iter().map(|__x| __x {} {}).collect::<Vec<_>>()",
        vec_render, op, scalar
    )
}
