use std::collections::BTreeMap;

use crate::ast::{Expr, MapKind, MatchPat, StructDef, Top, Ty, VariantDef};
use crate::diag::{Diag, DslResult, Span};
use crate::typed::{SpanKey, TypedFn};
use crate::PipelineOutput;

pub fn lower_program(pipeline: &PipelineOutput) -> DslResult<String> {
    let mut out = String::new();
    out.push_str("// Generated by dslc (MVP)\n");
    out.push_str("#![allow(dead_code)]\n\n");

    let mut structs = BTreeMap::new();
    let mut unions = BTreeMap::new();
    let mut variants: BTreeMap<String, (String, VariantDef)> = BTreeMap::new();
    let mut type_names = BTreeMap::new();
    let mut fn_names = BTreeMap::new();
    for t in &pipeline.tops {
        if let Top::Struct(sd) = t {
            structs.insert(sd.name.clone(), sd.clone());
            type_names.insert(sd.name.clone(), sd.rust_name.clone());
            if !sd.extern_ {
                out.push_str(&format!("#[derive(Debug, Clone)]\n"));
                out.push_str(&format!("pub struct {} {{\n", sd.rust_name));
                for f in &sd.fields {
                    out.push_str(&format!(
                        "    pub {}: {},\n",
                        f.rust_name,
                        ty_rust(&f.ty, &type_names)
                    ));
                }
                out.push_str("}\n\n");
            }
        }
        if let Top::Union(ud) = t {
            unions.insert(ud.name.clone(), ud.clone());
            type_names.insert(ud.name.clone(), ud.rust_name.clone());
            for v in &ud.variants {
                variants.insert(v.name.clone(), (ud.name.clone(), v.clone()));
            }
        }
        if let Top::Func(fd) = t {
            fn_names.insert(fd.name.clone(), fd.rust_name.clone());
        }
    }

    for ud in unions.values() {
        if !ud.extern_ {
            out.push_str(&format!("#[derive(Debug, Clone)]\n"));
            out.push_str(&format!("pub enum {} {{\n", ud.rust_name));
            for v in &ud.variants {
                if v.fields.is_empty() {
                    out.push_str(&format!("    {},\n", v.rust_name));
                } else {
                    out.push_str(&format!("    {} {{\n", v.rust_name));
                    for f in &v.fields {
                        out.push_str(&format!(
                            "        {}: {},\n",
                            f.rust_name,
                            ty_rust(&f.ty, &type_names)
                        ));
                    }
                    out.push_str("    },\n");
                }
            }
            out.push_str("}\n\n");
        }
    }

    let mut typed_iter = pipeline.typechecked.typed_fns.iter();
    for t in &pipeline.tops {
        if let Top::Func(fd) = t {
            let typed = typed_iter.next().ok_or_else(|| {
                Diag::new("internal error: missing typed function").with_span(fd.span.clone())
            })?;
            if typed.def.name != fd.name {
                return Err(Diag::new("internal error: typed function order mismatch")
                    .with_span(fd.span.clone()));
            }
            if fd.extern_ {
                continue;
            }
            let is_main = fd.name == "main" && fd.params.is_empty();
            out.push_str(&format!("pub fn {}(", fd.rust_name));
            emit_params(&mut out, fd, typed, &type_names)?;
            if is_main {
                out.push_str(") {\n");
            } else {
                out.push_str(&format!(") -> {} {{\n", ty_rust(&typed.body.ty, &type_names)));
            }
            out.push_str("    ");
            out.push_str(&lower_expr(
                &fd.body,
                &typed.body.casts,
                &typed.body.types,
                &structs,
                &variants,
                &fn_names,
                &type_names,
            ));
            if is_main {
                out.push_str(";\n}\n\n");
            } else {
                out.push_str("\n}\n\n");
            }
        }
    }

    Ok(out)
}

fn emit_params(
    out: &mut String,
    fd: &crate::ast::FnDef,
    typed: &TypedFn,
    type_names: &BTreeMap<String, String>,
) -> DslResult<()> {
    let mut first = true;
    for p in &fd.params {
        if !first {
            out.push_str(", ");
        }
        first = false;
        let ty = typed.param_tys.get(&p.rust_name).ok_or_else(|| {
            Diag::new("internal error: missing param type").with_span(p.span.clone())
        })?;
        out.push_str(&format!("{}: {}", p.rust_name, ty_rust(ty, type_names)));
    }
    Ok(())
}

fn lower_expr(
    e: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    fn_names: &BTreeMap<String, String>,
    type_names: &BTreeMap<String, String>,
) -> String {
    let mut inner = match e {
        Expr::Int(v, sp) => render_int_literal(*v, sp, types),
        Expr::Float(v, _) => {
            let mut s = v.to_string();
            if !s.contains('.') && !s.contains('e') && !s.contains('E') {
                s.push_str(".0");
            }
            s
        }
        Expr::Str(s, _) => {
            let lit = format!("{:?}", s);
            format!("String::from({})", lit)
        }
        Expr::Pair { .. } => "/* invalid pair */".to_string(),
        Expr::Var(v, _) => v.clone(),
        Expr::If { cond, then_br, else_br, .. } => {
            let cond = lower_expr(cond, casts, types, structs, variants, fn_names, type_names);
            let then_br = lower_expr(then_br, casts, types, structs, variants, fn_names, type_names);
            if let Some(else_br) = else_br {
                let else_br =
                    lower_expr(else_br, casts, types, structs, variants, fn_names, type_names);
                format!("if {} {{ {} }} else {{ {} }}", cond, then_br, else_br)
            } else {
                format!("if {} {{ {} }} else {{ () }}", cond, then_br)
            }
        }
        Expr::Do { exprs, .. } => {
            let mut parts = Vec::new();
            for (idx, ex) in exprs.iter().enumerate() {
                let rendered = lower_expr(ex, casts, types, structs, variants, fn_names, type_names);
                if idx + 1 == exprs.len() {
                    parts.push(rendered);
                } else {
                    parts.push(format!("{};", rendered));
                }
            }
            format!("{{ {} }}", parts.join(" "))
        }
        Expr::Loop { body, .. } => {
            let body = lower_expr(body, casts, types, structs, variants, fn_names, type_names);
            format!("loop {{ {}; }}", body)
        }
        Expr::While { cond, body, .. } => {
            let cond = lower_expr(cond, casts, types, structs, variants, fn_names, type_names);
            let body = lower_expr(body, casts, types, structs, variants, fn_names, type_names);
            format!("loop {{ if !({}) {{ break; }} {}; }}", cond, body)
        }
        Expr::For { var, range, body, .. } => {
            lower_for_expr(var, range, body, casts, types, structs, variants, fn_names, type_names)
        }
        Expr::Break { value, .. } => {
            if let Some(v) = value {
                let v = lower_expr(v, casts, types, structs, variants, fn_names, type_names);
                format!("break {}", v)
            } else {
                "break".to_string()
            }
        }
        Expr::Continue { .. } => "continue".to_string(),
        Expr::MapLit { kind, entries, .. } => {
            let map_ty = match kind {
                MapKind::Hash => "std::collections::HashMap",
                MapKind::BTree => "std::collections::BTreeMap",
            };
            let mut parts = Vec::new();
            for (k, v) in entries {
                let k = lower_expr(k, casts, types, structs, variants, fn_names, type_names);
                let v = lower_expr(v, casts, types, structs, variants, fn_names, type_names);
                parts.push(format!("__m.insert({}, {});", k, v));
            }
            if parts.is_empty() {
                format!("{}::new()", map_ty)
            } else {
                format!(
                    "{{ let mut __m = {}::new(); {} __m }}",
                    map_ty,
                    parts.join(" ")
                )
            }
        }
        Expr::VecLit { elems, ann, .. } => {
            if elems.is_empty() {
                if let Some(Ty::Vec(inner)) = ann {
                    format!("Vec::<{}>::new()", ty_rust(inner, type_names))
                } else {
                    "vec![]".to_string()
                }
            } else {
                let rendered: Vec<String> = elems
                    .iter()
                    .map(|el| lower_expr(el, casts, types, structs, variants, fn_names, type_names))
                    .collect();
                format!("vec![{}]", rendered.join(", "))
            }
        }
        Expr::Field { base, field, span: _ } => {
            let base_ty = expr_ty(types, &base.span());
            if let Some(Ty::Vec(_)) = base_ty {
                let base_expr =
                    lower_expr(base, casts, types, structs, variants, fn_names, type_names);
                format!(
                    "({}).into_iter().map(|__x| __x.{}).collect::<Vec<_>>()",
                    base_expr, field
                )
            } else {
                format!(
                    "{}.{}",
                    lower_expr(base, casts, types, structs, variants, fn_names, type_names),
                    field
                )
            }
        }
        Expr::Match { scrutinee, arms, .. } => {
            let scrut =
                lower_expr(scrutinee, casts, types, structs, variants, fn_names, type_names);
            let mut rendered = String::new();
            rendered.push_str(&format!("match {} {{ ", scrut));
            for arm in arms {
                match &arm.pat {
                    MatchPat::Wildcard(_) => {
                        rendered.push_str("_ => ");
                    }
                    MatchPat::Variant { name, bindings, .. } => {
                        if let Some((union_name, vdef)) = variants.get(name) {
                            let union_rust = type_names
                                .get(union_name)
                                .cloned()
                                .unwrap_or_else(|| rust_type_name(union_name));
                            if vdef.fields.is_empty() {
                                rendered.push_str(&format!(
                                    "{}::{} => ",
                                    union_rust, vdef.rust_name
                                ));
                            } else {
                                let mut parts = Vec::new();
                                for (field, binding, _) in bindings {
                                    if binding == "_" {
                                        parts.push(format!("{}: _", field));
                                    } else {
                                        parts.push(format!("{}: {}", field, binding));
                                    }
                                }
                                rendered.push_str(&format!(
                                    "{}::{} {{ {} }} => ",
                                    union_rust,
                                    vdef.rust_name,
                                    parts.join(", ")
                                ));
                            }
                        } else {
                            rendered.push_str(&format!("{} => ", name));
                        }
                    }
                }
                let body =
                    lower_expr(&arm.body, casts, types, structs, variants, fn_names, type_names);
                rendered.push_str(&format!("{}, ", body));
            }
            rendered.push_str("}");
            rendered
        }
        Expr::Call { op, args, span } => {
            if (op == "dbg" || op == "std.io/dbg" || op == "core.fmt/dbg") && args.len() == 1 {
                return format!(
                    "println!(\"{{:?}}\", {})",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.fmt/format" && args.len() == 1 {
                return format!(
                    "format!(\"{{:?}}\", {})",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.fmt/pretty" && args.len() == 1 {
                return format!(
                    "format!(\"{{:#?}}\", {})",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if (op == "core.fmt/print" || op == "core.fmt/println") && !args.is_empty() {
                let macro_name = if op == "core.fmt/print" {
                    "print"
                } else {
                    "println"
                };
                if let Expr::Str(s, _) = &args[0] {
                    let fmt = format!("{:?}", s);
                    if args.len() == 1 {
                        return format!("{}!({})", macro_name, fmt);
                    }
                    let rendered: Vec<String> = args[1..]
                        .iter()
                        .map(|el| lower_expr(el, casts, types, structs, variants, fn_names, type_names))
                        .collect();
                    return format!("{}!({}, {})", macro_name, fmt, rendered.join(", "));
                }
            }
            if op == "core.hashmap/new" || op == "core.btreemap/new" {
                let map_ty = if op == "core.hashmap/new" {
                    "std::collections::HashMap"
                } else {
                    "std::collections::BTreeMap"
                };
                if args.is_empty() {
                    return format!("{}::new()", map_ty);
                }
                let mut parts = Vec::new();
                for entry in args {
                    if let Expr::Pair { key, val, .. } = entry {
                        let k = lower_expr(key, casts, types, structs, variants, fn_names, type_names);
                        let v = lower_expr(val, casts, types, structs, variants, fn_names, type_names);
                        parts.push(format!("__m.insert({}, {});", k, v));
                    }
                }
                if !parts.is_empty() {
                    return format!(
                        "{{ let mut __m = {}::new(); {} __m }}",
                        map_ty,
                        parts.join(" ")
                    );
                }
            }
            if op == "core.vec/len" && args.len() == 1 {
                return format!(
                    "({}).len()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.vec/is-empty" && args.len() == 1 {
                return format!(
                    "({}).is_empty()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.vec/get" && args.len() == 2 {
                let v = lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                let idx = lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                return format!("({})[({}) as usize].clone()", v, idx);
            }
            if op == "core.vec/set" && args.len() == 3 {
                let v = lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                let idx = lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                let val = lower_expr(&args[2], casts, types, structs, variants, fn_names, type_names);
                return format!(
                    "{{ let mut __v = ({}).clone(); __v[({}) as usize] = {}; () }}",
                    v, idx, val
                );
            }
            if op == "core.str/len" && args.len() == 1 {
                return format!(
                    "({}).len()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.str/is-empty" && args.len() == 1 {
                return format!(
                    "({}).is_empty()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.str/trim" && args.len() == 1 {
                return format!(
                    "({}).trim().to_string()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.str/split" && args.len() == 2 {
                let s = lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                let sep =
                    lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                return format!(
                    "({}).split(({}).as_str()).map(String::from).collect::<Vec<_>>()",
                    s, sep
                );
            }
            if op == "core.str/join" && args.len() == 2 {
                let items =
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                let sep =
                    lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                return format!("({}).join(({}).as_str())", items, sep);
            }
            if op == "core.option/some" && args.len() == 1 {
                return format!(
                    "Some({})",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.option/none" && args.is_empty() {
                if let Some(Ty::Option(inner)) = expr_ty(types, span) {
                    let inner = *inner;
                    if matches!(inner, Ty::Unknown) {
                        return "Option::<()>::None".to_string();
                    }
                    return format!("Option::<{}>::None", ty_rust(&inner, type_names));
                }
                return "Option::<()>::None".to_string();
            }
            if op == "core.result/ok" && args.len() == 1 {
                let val =
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                if let Some(Ty::Result(ok_ty, err_ty)) = expr_ty(types, span) {
                    let ok = ty_rust_default(&ok_ty, type_names, "_");
                    let err = ty_rust_default(&err_ty, type_names, "()");
                    return format!("Result::<{}, {}>::Ok({})", ok, err, val);
                }
                return format!("Result::<_, ()>::Ok({})", val);
            }
            if op == "core.result/err" && args.len() == 1 {
                let val =
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                if let Some(Ty::Result(ok_ty, err_ty)) = expr_ty(types, span) {
                    let ok = ty_rust_default(&ok_ty, type_names, "()");
                    let err = ty_rust_default(&err_ty, type_names, "_");
                    return format!("Result::<{}, {}>::Err({})", ok, err, val);
                }
                return format!("Result::<(), _>::Err({})", val);
            }
            if op == "core.option/is-some" && args.len() == 1 {
                return format!(
                    "({}).is_some()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.option/is-none" && args.len() == 1 {
                return format!(
                    "({}).is_none()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.option/unwrap" && args.len() == 1 {
                return format!(
                    "({}).unwrap()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.option/unwrap-or" && args.len() == 2 {
                let opt =
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                let fallback =
                    lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                return format!("({}).unwrap_or({})", opt, fallback);
            }
            if op == "core.result/ok" && args.len() == 1 {
                return format!(
                    "Ok({})",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.result/err" && args.len() == 1 {
                return format!(
                    "Err({})",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.result/is-ok" && args.len() == 1 {
                return format!(
                    "({}).is_ok()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.result/is-err" && args.len() == 1 {
                return format!(
                    "({}).is_err()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.result/unwrap" && args.len() == 1 {
                return format!(
                    "({}).unwrap()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if op == "core.result/unwrap-or" && args.len() == 2 {
                let res =
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                let fallback =
                    lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                return format!("({}).unwrap_or({})", res, fallback);
            }
            if op == "core.hashmap/get" || op == "core.btreemap/get" {
                if args.len() == 2 {
                    let map =
                        lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                    let key =
                        lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                    return format!("({}).get(&{}).cloned()", map, key);
                }
            }
            if op == "core.hashmap/contains" || op == "core.btreemap/contains" {
                if args.len() == 2 {
                    let map =
                        lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                    let key =
                        lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                    return format!("({}).contains_key(&{})", map, key);
                }
            }
            if op == "core.hashmap/len" || op == "core.btreemap/len" {
                if args.len() == 1 {
                    return format!(
                        "({}).len()",
                        lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                    );
                }
            }
            if op == "core.hashmap/is-empty" || op == "core.btreemap/is-empty" {
                if args.len() == 1 {
                    return format!(
                        "({}).is_empty()",
                        lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                    );
                }
            }
            if op == "core.hashmap/insert" || op == "core.btreemap/insert" {
                if args.len() == 3 {
                    let map =
                        lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                    let key =
                        lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                    let val =
                        lower_expr(&args[2], casts, types, structs, variants, fn_names, type_names);
                    return format!(
                        "{{ let mut __m = ({}).clone(); __m.insert({}, {}); __m }}",
                        map, key, val
                    );
                }
            }
            if op == "core.hashmap/remove" || op == "core.btreemap/remove" {
                if args.len() == 2 {
                    let map =
                        lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                    let key =
                        lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                    return format!(
                        "{{ let mut __m = ({}).clone(); __m.remove(&{}); __m }}",
                        map, key
                    );
                }
            }
            if op == "core.num/abs" && args.len() == 1 {
                return format!(
                    "({}).abs()",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names)
                );
            }
            if (op == "core.num/min" || op == "core.num/max") && args.len() == 2 {
                let a = lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                let b = lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                let meth = if op == "core.num/min" { "min" } else { "max" };
                return format!("({}).{}({})", a, meth, b);
            }
            if op == "core.num/clamp" && args.len() == 3 {
                let x = lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names);
                let lo = lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names);
                let hi = lower_expr(&args[2], casts, types, structs, variants, fn_names, type_names);
                return format!("({}).clamp({}, {})", x, lo, hi);
            }
            if let Some(sd) = structs.get(op) {
                let rendered: Vec<String> = args
                    .iter()
                    .map(|el| lower_expr(el, casts, types, structs, variants, fn_names, type_names))
                    .collect();
                let mut parts = Vec::new();
                for (field, expr) in sd.fields.iter().zip(rendered.iter()) {
                    parts.push(format!("{}: {}", field.rust_name, expr));
                }
                return format!("{} {{ {} }}", sd.rust_name, parts.join(", "));
            }
            if let Some((union_name, vdef)) = variants.get(op) {
                let union_rust = type_names
                    .get(union_name)
                    .cloned()
                    .unwrap_or_else(|| rust_type_name(union_name));
                let rendered: Vec<String> = args
                    .iter()
                    .map(|el| lower_expr(el, casts, types, structs, variants, fn_names, type_names))
                    .collect();
                let mut parts = Vec::new();
                for (field, expr) in vdef.fields.iter().zip(rendered.iter()) {
                    parts.push(format!("{}: {}", field.rust_name, expr));
                }
                return if vdef.fields.is_empty() {
                    format!("{}::{}", union_rust, vdef.rust_name)
                } else {
                    format!("{}::{} {{ {} }}", union_rust, vdef.rust_name, parts.join(", "))
                };
            }
            if args.len() == 2 && ["+", "-", "*", "/"].contains(&op.as_str()) {
                let left_ty = expr_ty(types, &args[0].span());
                let right_ty = expr_ty(types, &args[1].span());
                if let (Some(Ty::Vec(_)), Some(right_ty)) = (left_ty.clone(), right_ty.clone()) {
                    return vec_scalar_binop(
                        op,
                        &args[0],
                        &args[1],
                        casts,
                        types,
                        structs,
                        variants,
                        fn_names,
                        type_names,
                        true,
                        &right_ty,
                    );
                }
                if let (Some(left_ty), Some(Ty::Vec(_))) = (left_ty.clone(), right_ty.clone()) {
                    return vec_scalar_binop(
                        op,
                        &args[0],
                        &args[1],
                        casts,
                        types,
                        structs,
                        variants,
                        fn_names,
                        type_names,
                        false,
                        &left_ty,
                    );
                }
                format!(
                    "({} {} {})",
                    lower_expr(&args[0], casts, types, structs, variants, fn_names, type_names),
                    op,
                    lower_expr(&args[1], casts, types, structs, variants, fn_names, type_names)
                )
            } else {
                let rendered: Vec<String> = args
                    .iter()
                    .map(|el| lower_expr(el, casts, types, structs, variants, fn_names, type_names))
                    .collect();
                let name = fn_names.get(op).cloned().unwrap_or_else(|| rust_value_name(op));
                format!("{}({})", name, rendered.join(", "))
            }
        }
    };

    for ch in casts {
        if spans_eq(&e.span(), &ch.span) {
            inner = format!("({} as {})", inner, ch.target.rust());
            break;
        }
    }
    inner
}

fn spans_eq(a: &Span, b: &Span) -> bool {
    a.start.byte == b.start.byte && a.end.byte == b.end.byte
}

fn expr_ty(types: &BTreeMap<SpanKey, Ty>, span: &Span) -> Option<Ty> {
    types.get(&SpanKey::new(span)).cloned()
}

fn render_int_literal(v: i64, sp: &Span, types: &BTreeMap<SpanKey, Ty>) -> String {
    let suffix = match expr_ty(types, sp) {
        Some(Ty::Named(name)) if is_int_type(&name) => name,
        Some(Ty::Named(name)) if is_uint_type(&name) => name,
        _ => "i32".to_string(),
    };
    format!("{}{}", v, suffix)
}

fn is_int_type(name: &str) -> bool {
    matches!(name, "i8" | "i16" | "i32" | "i64" | "isize")
}

fn is_uint_type(name: &str) -> bool {
    matches!(name, "u8" | "u16" | "u32" | "u64" | "usize")
}

fn vec_scalar_binop(
    op: &str,
    left: &Expr,
    right: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    fn_names: &BTreeMap<String, String>,
    type_names: &BTreeMap<String, String>,
    vec_on_left: bool,
    scalar_ty: &Ty,
) -> String {
    let vec_expr = if vec_on_left { left } else { right };
    let scalar_expr = if vec_on_left { right } else { left };
    let vec_render = lower_expr(vec_expr, casts, types, structs, variants, fn_names, type_names);
    let scalar_render =
        lower_expr(scalar_expr, casts, types, structs, variants, fn_names, type_names);
    let scalar = match scalar_ty {
        Ty::Named(_) => scalar_render,
        _ => scalar_render,
    };
    format!(
        "({}).into_iter().map(|__x| __x {} {}).collect::<Vec<_>>()",
        vec_render, op, scalar
    )
}

fn lower_for_expr(
    var: &str,
    range: &crate::ast::RangeExpr,
    body: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    fn_names: &BTreeMap<String, String>,
    type_names: &BTreeMap<String, String>,
) -> String {
    let start = lower_expr(&range.start, casts, types, structs, variants, fn_names, type_names);
    let end = lower_expr(&range.end, casts, types, structs, variants, fn_names, type_names);
    let ty = expr_ty(types, &range.start.span());
    let step = if let Some(step) = &range.step {
        lower_expr(step, casts, types, structs, variants, fn_names, type_names)
    } else {
        default_step_for_ty(ty.as_ref(), type_names)
    };
    let mut_decl = if let Some(ty) = ty.as_ref() {
        format!("let mut {}: {} = __start - __step;", var, ty_rust(ty, type_names))
    } else {
        format!("let mut {} = __start - __step;", var)
    };
    let cmp = if range.inclusive { "<=" } else { "<" };
    let body_render = lower_expr(body, casts, types, structs, variants, fn_names, type_names);
    format!(
        "{{ let __start = {start}; let __end = {end}; let __step = {step}; {mut_decl} loop {{ {var} = {var} + __step; if !({var} {cmp} __end) {{ break; }} {body_render}; }} }}",
        start = start,
        end = end,
        step = step,
        mut_decl = mut_decl,
        var = var,
        cmp = cmp,
        body_render = body_render
    )
}

fn default_step_for_ty(ty: Option<&Ty>, type_names: &BTreeMap<String, String>) -> String {
    if let Some(Ty::Named(name)) = ty {
        if is_float_type(name) {
            if name == "f32" {
                return "1.0f32".to_string();
            }
            return "1.0".to_string();
        }
        if is_int_type(name) || is_uint_type(name) {
            return format!("1{}", name);
        }
        if name == "string" {
            return "1".to_string();
        }
        let rust_name = ty_rust(&Ty::Named(name.clone()), type_names);
        return format!("1{}", rust_name);
    }
    "1".to_string()
}

fn is_float_type(name: &str) -> bool {
    matches!(name, "f32" | "f64")
}

fn rust_type_name(name: &str) -> String {
    let mut out = String::new();
    for part in name.split(|c| c == '-' || c == '_') {
        if part.is_empty() {
            continue;
        }
        let mut chars = part.chars();
        if let Some(c) = chars.next() {
            out.push(c.to_ascii_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn ty_rust(ty: &Ty, type_names: &BTreeMap<String, String>) -> String {
    match ty {
        Ty::Named(s) => {
            if matches!(
                s.as_str(),
                "i32"
                    | "i64"
                    | "u32"
                    | "u64"
                    | "f32"
                    | "f64"
                    | "bool"
                    | "usize"
                    | "isize"
                    | "()"
                    | "string"
            ) {
                if s == "string" {
                    "String".to_string()
                } else {
                    s.clone()
                }
            } else {
                type_names
                    .get(s)
                    .cloned()
                    .unwrap_or_else(|| rust_type_name(s))
            }
        }
        Ty::Vec(inner) => format!("Vec<{}>", ty_rust(inner, type_names)),
        Ty::Option(inner) => format!("Option<{}>", ty_rust(inner, type_names)),
        Ty::Result(ok, err) => format!(
            "Result<{}, {}>",
            ty_rust(ok, type_names),
            ty_rust(err, type_names)
        ),
        Ty::Map(kind, k, v) => {
            let name = match kind {
                MapKind::Hash => "std::collections::HashMap",
                MapKind::BTree => "std::collections::BTreeMap",
            };
            format!(
                "{}<{}, {}>",
                name,
                ty_rust(k, type_names),
                ty_rust(v, type_names)
            )
        }
        Ty::Unknown => "_".to_string(),
    }
}

fn ty_rust_default(ty: &Ty, type_names: &BTreeMap<String, String>, default: &str) -> String {
    if matches!(ty, Ty::Unknown) {
        default.to_string()
    } else {
        ty_rust(ty, type_names)
    }
}

fn rust_value_name(name: &str) -> String {
    name.replace('-', "_")
}
