use std::collections::{BTreeMap, BTreeSet};

use crate::ast::{Expr, MapKind, MatchPat, StructDef, Top, Ty, VariantDef};
use crate::diag::{Diag, DslResult, Span};
use crate::typed::{GenericBound, ParamMode, SpanKey, TypedFn};
use crate::PipelineOutput;

const ALLOW_LINTS: &[&str] = &[
    "dead_code",
    "unused_parens",
    "clippy::redundant_pattern",
    "non_shorthand_field_patterns",
    "unused_braces",
    "unused_imports",
    "non_upper_case_globals",
];

type FnNameMap = BTreeMap<(String, usize), String>;

pub fn lower_program(pipeline: &PipelineOutput) -> DslResult<String> {
    let mut out = String::new();
    out.push_str("// Generated by dslc compiler for Darcy lang\n");
    emit_allow_lints(&mut out);
    out.push_str("use std::sync::Arc;\n\n");
    emit_pseudo_traits(&mut out, &pipeline.typechecked.typed_fns);
    out.push('\n');

    let mut structs = BTreeMap::new();
    let mut unions = BTreeMap::new();
    let mut variants: BTreeMap<String, (String, VariantDef)> = BTreeMap::new();
    let mut type_names = BTreeMap::new();
    let mut fn_names: FnNameMap = BTreeMap::new();
    let mut def_names = BTreeMap::new();
    let mut fn_overload_counts: BTreeMap<String, usize> = BTreeMap::new();
    for t in &pipeline.tops {
        if let Top::Func(fd) = t {
            *fn_overload_counts.entry(fd.name.clone()).or_insert(0) += 1;
        }
    }
    let fn_env = &pipeline.typechecked.fn_env;
    let auto_clones = &pipeline.typechecked.auto_clones;
    for t in &pipeline.tops {
        if let Top::Struct(sd) = t {
            let resolved = pipeline
                .typechecked
                .env
                .structs
                .get(&sd.name)
                .unwrap_or(sd)
                .clone();
            structs.insert(resolved.name.clone(), resolved.clone());
            type_names.insert(resolved.name.clone(), resolved.rust_name.clone());
            if !resolved.extern_ {
                out.push_str(&format!("#[derive(Debug, Clone)]\n"));
                out.push_str(&format!("pub struct {} {{\n", resolved.rust_name));
                for f in &resolved.fields {
                    out.push_str(&format!(
                        "    pub {}: {},\n",
                        f.rust_name,
                        ty_rust(&f.ty, &type_names)
                    ));
                }
                out.push_str("}\n\n");
                out.push_str(&format!(
                    "impl std::fmt::Display for {} {{\n",
                    resolved.rust_name
                ));
                out.push_str(
                    "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n",
                );
                out.push_str("        write!(f, \"{:?}\", self)\n");
                out.push_str("    }\n");
                out.push_str("}\n\n");
            }
        }
        if let Top::Union(ud) = t {
            let resolved = pipeline
                .typechecked
                .env
                .unions
                .get(&ud.name)
                .unwrap_or(ud)
                .clone();
            unions.insert(resolved.name.clone(), resolved.clone());
            type_names.insert(resolved.name.clone(), resolved.rust_name.clone());
            for v in &resolved.variants {
                variants.insert(v.name.clone(), (resolved.name.clone(), v.clone()));
            }
        }
        if let Top::Func(fd) = t {
            let rust_name = if fn_overload_counts.get(&fd.name).copied().unwrap_or(0) > 1 {
                format!("{}__arity{}", fd.rust_name, fd.params.len())
            } else {
                fd.rust_name.clone()
            };
            fn_names.insert((fd.name.clone(), fd.params.len()), rust_name);
        }
        if let Top::Def(d) = t {
            def_names.insert(d.name.clone(), d.rust_name.clone());
        }
    }

    for ud in unions.values() {
        if !ud.extern_ {
            out.push_str(&format!("#[derive(Debug, Clone)]\n"));
            out.push_str(&format!("pub enum {} {{\n", ud.rust_name));
            for v in &ud.variants {
                if v.fields.is_empty() {
                    out.push_str(&format!("    {},\n", v.rust_name));
                } else {
                    out.push_str(&format!("    {} {{\n", v.rust_name));
                    for f in &v.fields {
                        out.push_str(&format!(
                            "        {}: {},\n",
                            f.rust_name,
                            ty_rust(&f.ty, &type_names)
                        ));
                    }
                    out.push_str("    },\n");
                }
            }
            out.push_str("}\n\n");
            out.push_str(&format!("impl std::fmt::Display for {} {{\n", ud.rust_name));
            out.push_str(
                "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n",
            );
            out.push_str("        write!(f, \"{:?}\", self)\n");
            out.push_str("    }\n");
            out.push_str("}\n\n");
        }
    }

    if !def_names.is_empty() {
        out.push_str("use std::sync::LazyLock;\n\n");
    }

    let mut typed_def_iter = pipeline.typechecked.typed_defs.iter();
    let empty_mutated = BTreeSet::new();
    for t in &pipeline.tops {
        if let Top::Def(d) = t {
            let typed = typed_def_iter.next().ok_or_else(|| {
                Diag::new("internal error: missing typed def").with_span(d.span.clone())
            })?;
            if typed.def.name != d.name {
                return Err(
                    Diag::new("internal error: typed def order mismatch").with_span(d.span.clone())
                );
            }
            let ty = ty_rust(&typed.body.ty, &type_names);
            let expr = lower_expr(
                &typed.body.expr,
                &typed.body.casts,
                &typed.body.types,
                &structs,
                &variants,
                &fn_names,
                &def_names,
                &type_names,
                fn_env,
                auto_clones,
                &empty_mutated,
            );
            out.push_str(&format!(
                "static {}: LazyLock<{}> = LazyLock::new(|| {});\n\n",
                d.rust_name, ty, expr
            ));
        }
    }

    let mut top_fn_names: BTreeSet<(String, usize)> = BTreeSet::new();
    for t in &pipeline.tops {
        if let Top::Func(fd) = t {
            top_fn_names.insert((fd.name.clone(), fd.params.len()));
        }
    }
    let mut typed_fn_map: BTreeMap<(String, usize), &TypedFn> = BTreeMap::new();
    for f in &pipeline.typechecked.typed_fns {
        typed_fn_map.insert((f.def.name.clone(), f.def.params.len()), f);
    }
    for t in &pipeline.tops {
        if let Top::Func(fd) = t {
            let typed = match typed_fn_map.get(&(fd.name.clone(), fd.params.len())) {
                Some(v) => *v,
                None => continue,
            };
            if fd.extern_ {
                continue;
            }
            let is_main = fd.rust_name == "main";
            let mut generics = BTreeSet::new();
            for ty in typed.param_tys.values() {
                collect_generic_ids(ty, &mut generics);
            }
            if !is_main {
                collect_generic_ids(&typed.body.ty, &mut generics);
            }
            let generics = render_generics(&generics, &typed.generic_bounds, &type_names);
            let vis = if fd.exported || is_main { "pub " } else { "" };
            let emitted_name = fn_names
                .get(&(fd.name.clone(), fd.params.len()))
                .cloned()
                .unwrap_or_else(|| fd.rust_name.clone());
            out.push_str(&format!("{}fn {}{}(", vis, emitted_name, generics));
            emit_params(&mut out, fd, typed, &type_names)?;
            if is_main {
                out.push_str(") {\n");
            } else {
                out.push_str(&format!(
                    ") -> {} {{\n",
                    ty_rust(&typed.body.ty, &type_names)
                ));
            }
            out.push_str("    ");
            out.push_str(&lower_fn_body(
                fd,
                typed,
                &typed.body.expr,
                &typed.body.casts,
                &typed.body.types,
                &structs,
                &variants,
                &fn_names,
                &def_names,
                &type_names,
                fn_env,
                auto_clones,
                &typed.mutated,
            ));
            if is_main {
                out.push_str(";\n}\n\n");
            } else {
                out.push_str("\n}\n\n");
            }
        }
    }

    for f in &pipeline.typechecked.typed_fns {
        if top_fn_names.contains(&(f.def.name.clone(), f.def.params.len())) {
            continue;
        }
        if f.def.extern_ {
            continue;
        }
        let mut generics = BTreeSet::new();
        for ty in f.param_tys.values() {
            collect_generic_ids(ty, &mut generics);
        }
        collect_generic_ids(&f.body.ty, &mut generics);
        let generics = render_generics(&generics, &f.generic_bounds, &type_names);
        out.push_str(&format!("fn {}{}(", f.def.rust_name, generics));
        emit_params(&mut out, &f.def, f, &type_names)?;
        out.push_str(&format!(") -> {} {{\n", ty_rust(&f.body.ty, &type_names)));
        out.push_str("    ");
        out.push_str(&lower_fn_body(
            &f.def,
            f,
            &f.body.expr,
            &f.body.casts,
            &f.body.types,
            &structs,
            &variants,
            &fn_names,
            &def_names,
            &type_names,
            fn_env,
            auto_clones,
            &f.mutated,
        ));
        out.push_str("\n}\n\n");
    }

    Ok(out)
}

fn emit_allow_lints(out: &mut String) {
    for lint in ALLOW_LINTS {
        out.push_str(&format!("#![allow({})]\n", lint));
    }
}

#[allow(clippy::too_many_arguments)]
fn lower_fn_body(
    fd: &crate::ast::FnDef,
    typed: &TypedFn,
    expr: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    fn_names: &FnNameMap,
    def_names: &BTreeMap<String, String>,
    type_names: &BTreeMap<String, String>,
    fn_env: &crate::typecheck::FnEnv,
    auto_clones: &BTreeSet<SpanKey>,
    mutated: &BTreeSet<String>,
) -> String {
    lower_self_tail_recursive_body(
        fd,
        typed,
        expr,
        casts,
        types,
        structs,
        variants,
        fn_names,
        def_names,
        type_names,
        fn_env,
        auto_clones,
        mutated,
    )
    .unwrap_or_else(|| {
        lower_expr(
            expr,
            casts,
            types,
            structs,
            variants,
            fn_names,
            def_names,
            type_names,
            fn_env,
            auto_clones,
            mutated,
        )
    })
}

#[allow(clippy::too_many_arguments)]
fn lower_self_tail_recursive_body(
    fd: &crate::ast::FnDef,
    typed: &TypedFn,
    expr: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    fn_names: &FnNameMap,
    def_names: &BTreeMap<String, String>,
    type_names: &BTreeMap<String, String>,
    fn_env: &crate::typecheck::FnEnv,
    auto_clones: &BTreeSet<SpanKey>,
    mutated: &BTreeSet<String>,
) -> Option<String> {
    if !has_self_tail_call(expr, &fd.name, fd.params.len(), true) {
        return None;
    }
    let param_modes: Vec<ParamMode> = fd
        .params
        .iter()
        .map(|p| {
            typed
                .param_modes
                .get(&p.rust_name)
                .copied()
                .unwrap_or(ParamMode::ByVal)
        })
        .collect();
    let mut setup = Vec::new();
    for p in &fd.params {
        setup.push(format!("let mut {} = {};", p.rust_name, p.rust_name));
    }
    let tail_stmt = lower_tail_stmt(
        expr,
        &fd.name,
        &fd.params,
        &param_modes,
        casts,
        types,
        structs,
        variants,
        fn_names,
        def_names,
        type_names,
        fn_env,
        auto_clones,
        mutated,
    );
    Some(format!(
        "{{ {} loop {{ {} }} }}",
        setup.join(" "),
        tail_stmt
    ))
}

fn has_self_tail_call(expr: &Expr, fn_name: &str, arity: usize, tail: bool) -> bool {
    match expr {
        Expr::Call { op, args, .. } => tail && op == fn_name && args.len() == arity,
        Expr::If {
            cond,
            then_br,
            else_br,
            ..
        } => {
            has_self_tail_call(cond, fn_name, arity, false)
                || has_self_tail_call(then_br, fn_name, arity, tail)
                || else_br
                    .as_ref()
                    .map(|e| has_self_tail_call(e, fn_name, arity, tail))
                    .unwrap_or(false)
        }
        Expr::Do { exprs, .. } => {
            for (idx, e) in exprs.iter().enumerate() {
                let in_tail = tail && idx + 1 == exprs.len();
                if has_self_tail_call(e, fn_name, arity, in_tail) {
                    return true;
                }
            }
            false
        }
        Expr::Let { bindings, body, .. } => {
            for b in bindings {
                if has_self_tail_call(&b.expr, fn_name, arity, false) {
                    return true;
                }
            }
            has_self_tail_call(body, fn_name, arity, tail)
        }
        Expr::Ascribe { expr, .. } | Expr::Cast { expr, .. } => {
            has_self_tail_call(expr, fn_name, arity, tail)
        }
        _ => false,
    }
}

#[allow(clippy::too_many_arguments)]
fn lower_tail_stmt(
    expr: &Expr,
    fn_name: &str,
    params: &[crate::ast::Param],
    param_modes: &[ParamMode],
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    fn_names: &FnNameMap,
    def_names: &BTreeMap<String, String>,
    type_names: &BTreeMap<String, String>,
    fn_env: &crate::typecheck::FnEnv,
    auto_clones: &BTreeSet<SpanKey>,
    mutated: &BTreeSet<String>,
) -> String {
    match expr {
        Expr::Call { op, args, .. } if op == fn_name && args.len() == params.len() => {
            let mut parts = Vec::new();
            for (idx, (arg, mode)) in args.iter().zip(param_modes.iter()).enumerate() {
                let rendered = lower_expr(
                    arg,
                    casts,
                    types,
                    structs,
                    variants,
                    fn_names,
                    def_names,
                    type_names,
                    fn_env,
                    auto_clones,
                    mutated,
                );
                let arg_value = match mode {
                    ParamMode::ByRef => format!("&{}", rendered),
                    ParamMode::ByRefNoAmp | ParamMode::ByVal => rendered,
                };
                parts.push(format!("let __tco_arg_{} = {};", idx, arg_value));
            }
            for (idx, p) in params.iter().enumerate() {
                parts.push(format!("{} = __tco_arg_{};", p.rust_name, idx));
            }
            parts.push("continue;".to_string());
            format!("{{ {} }}", parts.join(" "))
        }
        Expr::If {
            cond,
            then_br,
            else_br,
            ..
        } => {
            let cond = lower_expr(
                cond,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            let then_s = lower_tail_stmt(
                then_br,
                fn_name,
                params,
                param_modes,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            let else_s = else_br.as_ref().map_or_else(
                || "break ();".to_string(),
                |e| {
                    lower_tail_stmt(
                        e,
                        fn_name,
                        params,
                        param_modes,
                        casts,
                        types,
                        structs,
                        variants,
                        fn_names,
                        def_names,
                        type_names,
                        fn_env,
                        auto_clones,
                        mutated,
                    )
                },
            );
            format!("if {} {{ {} }} else {{ {} }}", cond, then_s, else_s)
        }
        Expr::Do { exprs, .. } => {
            if exprs.is_empty() {
                return "break ();".to_string();
            }
            let mut parts = Vec::new();
            for ex in exprs.iter().take(exprs.len() - 1) {
                parts.push(format!(
                    "{};",
                    lower_expr(
                        ex,
                        casts,
                        types,
                        structs,
                        variants,
                        fn_names,
                        def_names,
                        type_names,
                        fn_env,
                        auto_clones,
                        mutated,
                    )
                ));
            }
            parts.push(lower_tail_stmt(
                &exprs[exprs.len() - 1],
                fn_name,
                params,
                param_modes,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            ));
            format!("{{ {} }}", parts.join(" "))
        }
        Expr::Let { bindings, body, .. } => {
            let mut parts = Vec::new();
            for b in bindings {
                let expr = lower_expr(
                    &b.expr,
                    casts,
                    types,
                    structs,
                    variants,
                    fn_names,
                    def_names,
                    type_names,
                    fn_env,
                    auto_clones,
                    mutated,
                );
                let mut_kw = if mutated.contains(&b.rust_name) {
                    "mut "
                } else {
                    ""
                };
                if let Some(ann) = &b.ann {
                    parts.push(format!(
                        "let {}{}: {} = {};",
                        mut_kw,
                        b.rust_name,
                        ty_rust(ann, type_names),
                        expr
                    ));
                } else {
                    parts.push(format!("let {}{} = {};", mut_kw, b.rust_name, expr));
                }
            }
            parts.push(lower_tail_stmt(
                body,
                fn_name,
                params,
                param_modes,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            ));
            format!("{{ {} }}", parts.join(" "))
        }
        Expr::Ascribe { expr, .. } | Expr::Cast { expr, .. } => lower_tail_stmt(
            expr,
            fn_name,
            params,
            param_modes,
            casts,
            types,
            structs,
            variants,
            fn_names,
            def_names,
            type_names,
            fn_env,
            auto_clones,
            mutated,
        ),
        _ => format!(
            "break {};",
            lower_expr(
                expr,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            )
        ),
    }
}

fn emit_pseudo_traits(out: &mut String, fns: &[TypedFn]) {
    let mut needs_len = false;
    let mut needs_push = false;
    for f in fns {
        for bounds in f.generic_bounds.values() {
            for b in bounds {
                match b {
                    GenericBound::Len | GenericBound::IsEmpty => needs_len = true,
                    GenericBound::Push(_) => needs_push = true,
                    _ => {}
                }
            }
        }
    }
    if needs_len {
        out.push_str(
            "trait __DarcyLen {\n    fn len(&self) -> usize;\n    fn is_empty(&self) -> bool {\n        self.len() == 0\n    }\n}\n",
        );
        out.push_str(
            "impl<T> __DarcyLen for Arc<Vec<T>> {\n    fn len(&self) -> usize {\n        Vec::len(self)\n    }\n}\n",
        );
        out.push_str("impl __DarcyLen for String {\n    fn len(&self) -> usize {\n        String::len(self)\n    }\n}\n");
        out.push('\n');
    }
    if needs_push {
        out.push_str("trait __DarcyPush<T> {\n    fn push(&mut self, value: T);\n}\n");
        out.push_str(
            "impl<T> __DarcyPush<T> for Arc<Vec<T>> {\n    fn push(&mut self, value: T) {\n        let v = Arc::make_mut(self);\n        Vec::push(v, value)\n    }\n}\n\n",
        );
    }
}

fn collect_generic_ids(ty: &Ty, out: &mut BTreeSet<u32>) {
    match ty {
        Ty::Generic(id) => {
            out.insert(*id);
        }
        Ty::Vec(inner) | Ty::Set(inner) | Ty::Option(inner) => {
            collect_generic_ids(inner, out);
        }
        Ty::Result(ok, err) => {
            collect_generic_ids(ok, out);
            collect_generic_ids(err, out);
        }
        Ty::Map(_, k, v) => {
            collect_generic_ids(k, out);
            collect_generic_ids(v, out);
        }
        Ty::Union(items) => {
            for item in items {
                collect_generic_ids(item, out);
            }
        }
        Ty::Named(_) | Ty::Unknown => {}
    }
}

fn render_generics(
    generics: &BTreeSet<u32>,
    bounds: &BTreeMap<u32, Vec<GenericBound>>,
    type_names: &BTreeMap<String, String>,
) -> String {
    if generics.is_empty() {
        return String::new();
    }
    let mut parts = Vec::new();
    for id in generics {
        let name = format!("T{}", id);
        let mut rendered_bounds = BTreeSet::new();
        if let Some(list) = bounds.get(id) {
            for b in list {
                let rendered = match b {
                    GenericBound::Copy => "Copy".to_string(),
                    GenericBound::Clone => "Clone".to_string(),
                    GenericBound::Debug => "std::fmt::Debug".to_string(),
                    GenericBound::PartialEq => "PartialEq".to_string(),
                    GenericBound::PartialOrd => "PartialOrd".to_string(),
                    GenericBound::Add => format!("std::ops::Add<Output={}>", name),
                    GenericBound::Sub => format!("std::ops::Sub<Output={}>", name),
                    GenericBound::Mul => format!("std::ops::Mul<Output={}>", name),
                    GenericBound::Div => format!("std::ops::Div<Output={}>", name),
                    GenericBound::FromInt => "darcy_stdlib::rt::FromInt".to_string(),
                    GenericBound::Len | GenericBound::IsEmpty => "__DarcyLen".to_string(),
                    GenericBound::Push(inner) => {
                        format!("__DarcyPush<{}>", ty_rust(inner, type_names))
                    }
                };
                rendered_bounds.insert(rendered);
            }
        }
        if rendered_bounds.is_empty() {
            parts.push(name);
        } else {
            let list = rendered_bounds.into_iter().collect::<Vec<_>>().join(" + ");
            parts.push(format!("{}: {}", name, list));
        }
    }
    format!("<{}>", parts.join(", "))
}

fn emit_params(
    out: &mut String,
    fd: &crate::ast::FnDef,
    typed: &TypedFn,
    type_names: &BTreeMap<String, String>,
) -> DslResult<()> {
    let mut first = true;
    for p in &fd.params {
        if !first {
            out.push_str(", ");
        }
        first = false;
        let ty = typed.param_tys.get(&p.rust_name).ok_or_else(|| {
            Diag::new("internal error: missing param type").with_span(p.span.clone())
        })?;
        let mode = typed
            .param_modes
            .get(&p.rust_name)
            .copied()
            .unwrap_or(ParamMode::ByVal);
        let mut rendered = ty_rust(ty, type_names);
        if matches!(mode, ParamMode::ByRef) {
            rendered = format!("&{}", rendered);
        }
        let mut_name = if typed.mutated.contains(&p.rust_name) {
            format!("mut {}", p.rust_name)
        } else {
            p.rust_name.clone()
        };
        out.push_str(&format!("{}: {}", mut_name, rendered));
    }
    Ok(())
}

fn lower_expr(
    e: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    fn_names: &FnNameMap,
    def_names: &BTreeMap<String, String>,
    type_names: &BTreeMap<String, String>,
    fn_env: &crate::typecheck::FnEnv,
    auto_clones: &BTreeSet<SpanKey>,
    mutated: &BTreeSet<String>,
) -> String {
    // DRY macros to avoid repeating all 10 context arguments
    macro_rules! lower {
        ($e:expr) => {
            lower_expr(
                $e,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            )
        };
    }
    macro_rules! lower_idx {
        ($e:expr) => {
            lower_index_arg(
                $e,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            )
        };
    }

    let mut inner = match e {
        Expr::Int(v, sp) => render_int_literal(*v, sp, types),
        Expr::Float(v, _) => {
            let mut s = v.to_string();
            if !s.contains('.') && !s.contains('e') && !s.contains('E') {
                s.push_str(".0");
            }
            s
        }
        Expr::Str(s, _) => match parse_interpolated_string(s) {
            Some(parts) => {
                let mut fmt_template = String::new();
                let mut args = Vec::new();
                for part in parts {
                    match part {
                        InterpPart::Text(t) => {
                            fmt_template.push_str(&escape_format_braces(&t));
                        }
                        InterpPart::Expr(name) => {
                            fmt_template.push_str("{}");
                            let rust_name = rust_value_name(&name);
                            let value = if let Some(def) = def_names.get(&rust_name) {
                                format!("(*{}).clone()", def)
                            } else {
                                rust_name
                            };
                            args.push(format!("darcy_stdlib::rt::fmt_format({})", value));
                        }
                    }
                }
                let fmt_lit = format!("{:?}", fmt_template);
                if args.is_empty() {
                    format!("String::from({})", fmt_lit)
                } else {
                    format!("format!({}, {})", fmt_lit, args.join(", "))
                }
            }
            None => {
                let lit = format!("{:?}", s);
                format!("String::from({})", lit)
            }
        },
        Expr::Bool(v, _) => v.to_string(),
        Expr::Unit(_) => "()".to_string(),
        Expr::Keyword(s, _) => {
            let lit = format!("{:?}", s);
            format!("darcy_stdlib::rt::symbol({})", lit)
        }
        Expr::Pair { .. } => "/* invalid pair */".to_string(),
        Expr::Var(v, sp) => {
            let base = if let Some(def) = def_names.get(v) {
                format!("(*{}).clone()", def)
            } else {
                v.clone()
            };
            if matches!(expr_ty(types, sp), Some(Ty::Vec(_))) {
                if base.ends_with(".clone()") {
                    base
                } else {
                    format!("({}).clone()", base)
                }
            } else if auto_clones.contains(&SpanKey::new(sp)) {
                format!("({}).clone()", base)
            } else {
                base
            }
        }
        Expr::Ascribe { expr, .. } => lower!(expr),
        Expr::Cast { expr, ann, .. } => {
            let inner = lower!(expr);
            if matches!(ann, Ty::Named(name) if name == "usize") {
                format!("darcy_stdlib::rt::cast_usize({})", inner)
            } else {
                format!("({} as {})", inner, ann.rust())
            }
        }
        Expr::If {
            cond,
            then_br,
            else_br,
            ..
        } => {
            let cond = lower_expr(
                cond,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            let then_br = lower_expr(
                then_br,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            if let Some(else_br) = else_br {
                let else_br = lower_expr(
                    else_br,
                    casts,
                    types,
                    structs,
                    variants,
                    fn_names,
                    def_names,
                    type_names,
                    fn_env,
                    auto_clones,
                    mutated,
                );
                format!("if {} {{ {} }} else {{ {} }}", cond, then_br, else_br)
            } else {
                format!("if {} {{ {} }} else {{ () }}", cond, then_br)
            }
        }
        Expr::Do { exprs, .. } => {
            let mut parts = Vec::new();
            for (idx, ex) in exprs.iter().enumerate() {
                let rendered = lower_expr(
                    ex,
                    casts,
                    types,
                    structs,
                    variants,
                    fn_names,
                    def_names,
                    type_names,
                    fn_env,
                    auto_clones,
                    mutated,
                );
                if idx + 1 == exprs.len() {
                    parts.push(rendered);
                } else {
                    parts.push(format!("{};", rendered));
                }
            }
            format!("{{ {} }}", parts.join(" "))
        }
        Expr::Let { bindings, body, .. } => {
            let mut parts = Vec::new();
            for b in bindings {
                let expr = lower_expr(
                    &b.expr,
                    casts,
                    types,
                    structs,
                    variants,
                    fn_names,
                    def_names,
                    type_names,
                    fn_env,
                    auto_clones,
                    mutated,
                );
                let mut_kw = if mutated.contains(&b.rust_name) {
                    "mut "
                } else {
                    ""
                };
                if let Some(ann) = &b.ann {
                    parts.push(format!(
                        "let {}{}: {} = {};",
                        mut_kw,
                        b.rust_name,
                        ty_rust(ann, type_names),
                        expr
                    ));
                } else {
                    parts.push(format!("let {}{} = {};", mut_kw, b.rust_name, expr));
                }
            }
            let body = lower_expr(
                body,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            format!("{{ {} {} }}", parts.join(" "), body)
        }
        Expr::Set { name, expr, .. } => {
            let expr = lower!(expr);
            format!("{{ {} = {}; () }}", name, expr)
        }
        Expr::Lambda { params, body, .. } => {
            let mut rendered = Vec::new();
            for p in params {
                if let Some(ann) = &p.ann {
                    rendered.push(format!("{}: {}", p.rust_name, ty_rust(ann, type_names)));
                } else {
                    rendered.push(p.rust_name.clone());
                }
            }
            let body = lower_expr(
                body,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            format!("|{}| {{ {} }}", rendered.join(", "), body)
        }
        Expr::CallDyn { func, args, .. } => {
            let func = lower_expr(
                func,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            let rendered: Vec<String> = args.iter().map(|el| lower!(el)).collect();
            format!("({})({})", func, rendered.join(", "))
        }
        Expr::MethodCall {
            base, method, args, ..
        } => {
            let base_ty = expr_ty(types, &base.span());
            if args.is_empty() {
                if let Some(ty) = base_ty.as_ref() {
                    match ty {
                        Ty::Named(name) => {
                            if let Some(sd) = structs.get(name) {
                                if let Some(field) =
                                    sd.fields.iter().find(|f| f.rust_name == *method)
                                {
                                    let base = lower!(base);
                                    if matches!(field.ty, Ty::Vec(_)) {
                                        return format!("({}).{}.clone()", base, method);
                                    }
                                    return format!("({}).{}", base, method);
                                }
                            }
                        }
                        Ty::Vec(inner) => {
                            if let Ty::Named(name) = inner.as_ref() {
                                if let Some(sd) = structs.get(name) {
                                    if sd.fields.iter().any(|f| f.rust_name == *method) {
                                        let base = lower!(base);
                                        return format!(
                                            "Arc::new(({}).iter().map(|__x| __x.{}.clone()).collect::<Vec<_>>())",
                                            base, method
                                        );
                                    }
                                }
                            }
                        }
                        _ => {}
                    }
                }
            }
            let base = lower!(base);
            let rendered: Vec<String> = args.iter().map(|el| lower!(el)).collect();
            format!("({}).{}({})", base, method, rendered.join(", "))
        }
        Expr::Loop { body, .. } => {
            let body = lower_expr(
                body,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            format!("loop {{ {}; }}", body)
        }
        Expr::While { cond, body, .. } => {
            let cond = lower_expr(
                cond,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            let body = lower_expr(
                body,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            format!("loop {{ if !({}) {{ break; }} {}; }}", cond, body)
        }
        Expr::For {
            var, iter, body, ..
        } => lower_for_expr(
            var,
            iter,
            body,
            casts,
            types,
            structs,
            variants,
            fn_names,
            def_names,
            type_names,
            fn_env,
            auto_clones,
            mutated,
        ),
        Expr::Break { value, .. } => {
            if let Some(v) = value {
                let v = lower_expr(
                    v,
                    casts,
                    types,
                    structs,
                    variants,
                    fn_names,
                    def_names,
                    type_names,
                    fn_env,
                    auto_clones,
                    mutated,
                );
                format!("break {}", v)
            } else {
                "break".to_string()
            }
        }
        Expr::Continue { .. } => "continue".to_string(),
        Expr::MapLit { kind, entries, .. } => {
            let map_ty = match kind {
                MapKind::IMap => "darcy_stdlib::rt::IMap",
                MapKind::Hash => "std::collections::HashMap",
                MapKind::BTree => "std::collections::BTreeMap",
            };
            let mut parts = Vec::new();
            for (k, v) in entries {
                let k = lower_expr(
                    k,
                    casts,
                    types,
                    structs,
                    variants,
                    fn_names,
                    def_names,
                    type_names,
                    fn_env,
                    auto_clones,
                    mutated,
                );
                let v = lower_expr(
                    v,
                    casts,
                    types,
                    structs,
                    variants,
                    fn_names,
                    def_names,
                    type_names,
                    fn_env,
                    auto_clones,
                    mutated,
                );
                parts.push(format!("__m.insert({}, {});", k, v));
            }
            if parts.is_empty() {
                format!("{}::new()", map_ty)
            } else {
                format!(
                    "{{ let mut __m = {}::new(); {} __m }}",
                    map_ty,
                    parts.join(" ")
                )
            }
        }
        Expr::SetLit { elems, ann, .. } => {
            let mut parts = Vec::new();
            for el in elems {
                let el = lower!(el);
                parts.push(format!("__s.insert({});", el));
            }
            if parts.is_empty() {
                if let Some(Ty::Set(inner)) = ann {
                    format!(
                        "std::collections::HashSet::<{}>::new()",
                        ty_rust(inner, type_names)
                    )
                } else {
                    "std::collections::HashSet::new()".to_string()
                }
            } else {
                format!(
                    "{{ let mut __s = std::collections::HashSet::new(); {} __s }}",
                    parts.join(" ")
                )
            }
        }
        Expr::VecLit { elems, ann, .. } => {
            if elems.is_empty() {
                if let Some(Ty::Vec(inner)) = ann {
                    format!("Arc::new(Vec::<{}>::new())", ty_rust(inner, type_names))
                } else {
                    "Arc::new(vec![])".to_string()
                }
            } else {
                let rendered: Vec<String> = elems.iter().map(|el| lower!(el)).collect();
                format!("Arc::new(vec![{}])", rendered.join(", "))
            }
        }
        Expr::Field {
            base,
            field,
            span: _,
        } => {
            let base_ty = expr_ty(types, &base.span());
            if let Some(Ty::Vec(_)) = base_ty {
                let base_expr = lower!(base);
                format!(
                    "Arc::new(({}).iter().map(|__x| __x.{}.clone()).collect::<Vec<_>>())",
                    base_expr, field
                )
            } else {
                format!("{}.{}", lower!(base), field)
            }
        }
        Expr::Match {
            scrutinee, arms, ..
        } => {
            let scrut = lower_expr(
                scrutinee,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            let mut rendered = String::new();
            rendered.push_str(&format!("match {} {{ ", scrut));
            for arm in arms {
                match &arm.pat {
                    MatchPat::Wildcard(_) => {
                        rendered.push_str("_ => ");
                    }
                    MatchPat::Variant { name, bindings, .. } => {
                        if let Some((union_name, vdef)) = variants.get(name) {
                            let union_rust = type_names
                                .get(union_name)
                                .cloned()
                                .unwrap_or_else(|| rust_type_name(union_name));
                            if vdef.fields.is_empty() {
                                rendered
                                    .push_str(&format!("{}::{} => ", union_rust, vdef.rust_name));
                            } else {
                                let mut parts = Vec::new();
                                for (field, binding, _) in bindings {
                                    if binding == "_" {
                                        parts.push(format!("{}: _", field));
                                    } else {
                                        parts.push(format!("{}: {}", field, binding));
                                    }
                                }
                                rendered.push_str(&format!(
                                    "{}::{} {{ {} }} => ",
                                    union_rust,
                                    vdef.rust_name,
                                    parts.join(", ")
                                ));
                            }
                        } else {
                            rendered.push_str(&format!("{} => ", name));
                        }
                    }
                }
                let body = lower_expr(
                    &arm.body,
                    casts,
                    types,
                    structs,
                    variants,
                    fn_names,
                    def_names,
                    type_names,
                    fn_env,
                    auto_clones,
                    mutated,
                );
                rendered.push_str(&format!("{}, ", body));
            }
            rendered.push_str("}");
            rendered
        }
        Expr::Call { op, args, span } => {
            if op == "darcy.io/dbg" && args.len() == 1 {
                return format!("println!(\"{{:?}}\", {})", lower!(&args[0]));
            }
            if op == "darcy.fmt/format" && args.len() == 1 {
                return format!("format!(\"{{:?}}\", {})", lower!(&args[0]));
            }
            if op == "darcy.fmt/pretty" && args.len() == 1 {
                return format!("format!(\"{{:#?}}\", {})", lower!(&args[0]));
            }
            if (op == "darcy.fmt/print" || op == "darcy.fmt/println") && !args.is_empty() {
                let macro_name = if op == "darcy.fmt/print" {
                    "print"
                } else {
                    "println"
                };
                if args.len() == 1 {
                    let rendered = lower!(&args[0]);
                    return format!("{}!(\"{{}}\", {})", macro_name, rendered);
                }
                if let Expr::Str(s, _) = &args[0] {
                    let fmt = format!("{:?}", s);
                    let rendered: Vec<String> = args[1..].iter().map(|el| lower!(el)).collect();
                    return format!("{}!({}, {})", macro_name, fmt, rendered.join(", "));
                } else {
                    // Non-string-literal first argument (e.g., format! result)
                    let rendered: Vec<String> = args.iter().map(|el| lower!(el)).collect();
                    let fmt_parts = vec!["{}"; rendered.len()].join(" ");
                    return format!("{}!({:?}, {})", macro_name, fmt_parts, rendered.join(", "));
                }
            }
            if op == "darcy.vec/len" && args.len() == 1 {
                return format!("({}).len()", lower!(&args[0]));
            }
            if op == "darcy.vec/is-empty" && args.len() == 1 {
                return format!("(&({})).is_empty()", lower!(&args[0]));
            }
            if op == "darcy.vec/get" && args.len() == 2 {
                let v = lower!(&args[0]);
                let idx = lower_idx!(&args[1]);
                return format!("darcy_stdlib::rt::vec_get(&({}), {})", v, idx);
            }
            if op == "darcy.vec/set" && args.len() == 3 {
                let v = lower!(&args[0]);
                let idx = lower_idx!(&args[1]);
                let val = lower!(&args[2]);
                return format!("darcy_stdlib::rt::vec_set({}, {}, {})", v, idx, val);
            }
            if op == "darcy.vec/push" && args.len() == 2 {
                let v = lower!(&args[0]);
                let val = lower!(&args[1]);
                return format!("darcy_stdlib::rt::vec_push({}, {})", v, val);
            }
            if op == "darcy.vec/new" && args.is_empty() {
                return "darcy_stdlib::rt::vec_new()".to_string();
            }
            if op == "darcy.vec/repeat" && args.len() == 2 {
                let val = lower!(&args[0]);
                let n = lower_idx!(&args[1]);
                return format!("darcy_stdlib::rt::vec_repeat({}, {})", val, n);
            }
            if op == "darcy.vec/map" && args.len() == 2 {
                let f = lower!(&args[0]);
                let v = lower!(&args[1]);
                return format!("darcy_stdlib::rt::vec_map({}, {})", f, v);
            }
            if op == "darcy.vec/map2" && args.len() == 3 {
                let f = lower!(&args[0]);
                let v1 = lower!(&args[1]);
                let v2 = lower!(&args[2]);
                return format!("darcy_stdlib::rt::vec_map2({}, {}, {})", f, v1, v2);
            }
            if op == "darcy.vec/fold" && args.len() == 3 {
                let f = lower!(&args[0]);
                let init = lower!(&args[1]);
                let v = lower!(&args[2]);
                return format!("darcy_stdlib::rt::vec_fold({}, {}, {})", f, init, v);
            }
            if op == "darcy.vec/take" && args.len() == 2 {
                let v = lower!(&args[0]);
                let n = lower_idx!(&args[1]);
                return format!("darcy_stdlib::rt::vec_take({}, {})", v, n);
            }
            if op == "darcy.vec/range" && args.len() == 1 {
                let n = lower_idx!(&args[0]);
                return format!("darcy_stdlib::rt::vec_range({})", n);
            }
            if op == "darcy.vec/is-empty" && args.len() == 1 {
                return format!("({}).is_empty()", lower!(&args[0]));
            }
            if op == "darcy.string/len" && args.len() == 1 {
                return format!("({}).len()", lower!(&args[0]));
            }
            if op == "darcy.string/is-empty" && args.len() == 1 {
                return format!("({}).is_empty()", lower!(&args[0]));
            }
            if op == "darcy.string/trim" && args.len() == 1 {
                return format!("({}).trim().to_string()", lower!(&args[0]));
            }
            if op == "darcy.string/split" && args.len() == 2 {
                let s = lower!(&args[0]);
                let sep = lower!(&args[1]);
                return format!(
                    "Arc::new(({}).split(&{}).map(|part| part.to_string()).collect::<Vec<String>>())",
                    s, sep
                );
            }
            if op == "darcy.string/join" && args.len() == 2 {
                let items = lower!(&args[0]);
                let sep = lower!(&args[1]);
                return format!("(&({})).join((&({})).as_str())", items, sep);
            }
            if op == "darcy.option/some" && args.len() == 1 {
                return format!("Some({})", lower!(&args[0]));
            }
            if op == "darcy.option/none" && args.is_empty() {
                if let Some(Ty::Option(inner)) = expr_ty(types, span) {
                    let inner = *inner;
                    return format!("Option::<{}>::None", ty_rust_infer(&inner, type_names));
                }
                return "Option::<_>::None".to_string();
            }
            if op == "darcy.result/ok" && args.len() == 1 {
                let val = lower!(&args[0]);
                if let Some(Ty::Result(ok_ty, err_ty)) = expr_ty(types, span) {
                    let ok = ty_rust_infer(&ok_ty, type_names);
                    let err = ty_rust_infer(&err_ty, type_names);
                    return format!("Result::<{}, {}>::Ok({})", ok, err, val);
                }
                return format!("Result::<_, _>::Ok({})", val);
            }
            if op == "darcy.result/err" && args.len() == 1 {
                let val = lower!(&args[0]);
                if let Some(Ty::Result(ok_ty, err_ty)) = expr_ty(types, span) {
                    let ok = ty_rust_infer(&ok_ty, type_names);
                    let err = ty_rust_infer(&err_ty, type_names);
                    return format!("Result::<{}, {}>::Err({})", ok, err, val);
                }
                return format!("Result::<_, _>::Err({})", val);
            }
            if op == "darcy.option/is-some" && args.len() == 1 {
                return format!("({}).is_some()", lower!(&args[0]));
            }
            if op == "darcy.option/is-none" && args.len() == 1 {
                return format!("({}).is_none()", lower!(&args[0]));
            }
            if op == "darcy.option/unwrap" && args.len() == 1 {
                return format!("({}).unwrap()", lower!(&args[0]));
            }
            if op == "darcy.result/is-ok" && args.len() == 1 {
                return format!("({}).is_ok()", lower!(&args[0]));
            }
            if op == "darcy.option/unwrap-or" && args.len() == 2 {
                let opt = lower!(&args[0]);
                let fallback = lower!(&args[1]);
                return format!("({}).unwrap_or({})", opt, fallback);
            }
            if op == "darcy.result/is-err" && args.len() == 1 {
                return format!("({}).is_err()", lower!(&args[0]));
            }
            if op == "darcy.math/exp" && args.len() == 1 {
                return format!("({}).exp()", lower!(&args[0]));
            }
            if (op == "darcy.math/min" || op == "darcy.math/max") && args.len() == 2 {
                let lhs = lower!(&args[0]);
                let rhs = lower!(&args[1]);
                let method = if op == "darcy.math/min" { "min" } else { "max" };
                return format!("({}).{}({})", lhs, method, rhs);
            }
            if op == "darcy.math/clamp" && args.len() == 3 {
                let val = lower!(&args[0]);
                let lo = lower!(&args[1]);
                let hi = lower!(&args[2]);
                return format!("({}).clamp({}, {})", val, lo, hi);
            }
            if op == "darcy.math/abs" && args.len() == 1 {
                return format!("({}).abs()", lower!(&args[0]));
            }
            if op == "darcy.core/clone" && args.len() == 1 {
                return format!("({}).clone()", lower!(&args[0]));
            }
            if op == "darcy.result/unwrap" && args.len() == 1 {
                return format!("({}).unwrap()", lower!(&args[0]));
            }
            if op == "darcy.result/unwrap-or" && args.len() == 2 {
                let res = lower!(&args[0]);
                let fallback = lower!(&args[1]);
                return format!("({}).unwrap_or({})", res, fallback);
            }
            if op == "darcy.hash-map/new" || op == "darcy.imap/new" || op == "darcy.btree-map/new" {
                let map_ty = if op == "darcy.hash-map/new" {
                    "std::collections::HashMap"
                } else if op == "darcy.imap/new" {
                    "darcy_stdlib::rt::IMap"
                } else {
                    "std::collections::BTreeMap"
                };
                if args.is_empty() {
                    return format!("{}::new()", map_ty);
                }
                let mut parts = Vec::new();
                for entry in args {
                    match entry {
                        Expr::Pair { key, val, .. } => {
                            let k = lower_expr(
                                key,
                                casts,
                                types,
                                structs,
                                variants,
                                fn_names,
                                def_names,
                                type_names,
                                fn_env,
                                auto_clones,
                                mutated,
                            );
                            let v = lower_expr(
                                val,
                                casts,
                                types,
                                structs,
                                variants,
                                fn_names,
                                def_names,
                                type_names,
                                fn_env,
                                auto_clones,
                                mutated,
                            );
                            parts.push(format!("__m.insert({}, {});", k, v));
                        }
                        Expr::VecLit { elems, .. } if elems.len() == 2 => {
                            let k = lower_expr(
                                &elems[0],
                                casts,
                                types,
                                structs,
                                variants,
                                fn_names,
                                def_names,
                                type_names,
                                fn_env,
                                auto_clones,
                                mutated,
                            );
                            let v = lower_expr(
                                &elems[1],
                                casts,
                                types,
                                structs,
                                variants,
                                fn_names,
                                def_names,
                                type_names,
                                fn_env,
                                auto_clones,
                                mutated,
                            );
                            parts.push(format!("__m.insert({}, {});", k, v));
                        }
                        _ => {}
                    }
                }
                if !parts.is_empty() {
                    return format!(
                        "{{ let mut __m = {}::new(); {} __m }}",
                        map_ty,
                        parts.join(" ")
                    );
                }
            }
            if op == "darcy.hash-map/get" || op == "darcy.imap/get" || op == "darcy.btree-map/get" {
                if args.len() == 2 {
                    let map = lower!(&args[0]);
                    let key = lower!(&args[1]);
                    return format!("(&({})).get(&{}).cloned()", map, key);
                }
            }
            if op == "darcy.hash-map/contains"
                || op == "darcy.imap/contains"
                || op == "darcy.btree-map/contains"
            {
                if args.len() == 2 {
                    let map = lower!(&args[0]);
                    let key = lower!(&args[1]);
                    return format!("(&({})).contains_key(&{})", map, key);
                }
            }
            if op == "darcy.hash-map/len" || op == "darcy.imap/len" || op == "darcy.btree-map/len" {
                if args.len() == 1 {
                    return format!("(&({})).len()", lower!(&args[0]));
                }
            }
            if op == "darcy.hash-map/is-empty"
                || op == "darcy.imap/is-empty"
                || op == "darcy.btree-map/is-empty"
            {
                if args.len() == 1 {
                    return format!("(&({})).is_empty()", lower!(&args[0]));
                }
            }
            if op == "darcy.hash-map/insert"
                || op == "darcy.imap/insert"
                || op == "darcy.btree-map/insert"
            {
                if args.len() == 3 {
                    let map = lower!(&args[0]);
                    let key = lower!(&args[1]);
                    let val = lower!(&args[2]);
                    return format!(
                        "{{ let mut __m = ({}).clone(); __m.insert({}, {}); __m }}",
                        map, key, val
                    );
                }
            }
            if op == "darcy.hash-map/remove"
                || op == "darcy.imap/remove"
                || op == "darcy.btree-map/remove"
            {
                if args.len() == 2 {
                    let map = lower!(&args[0]);
                    let key = lower!(&args[1]);
                    if op == "darcy.imap/remove" {
                        return format!(
                            "{{ let mut __m = ({}).clone(); __m.shift_remove(&{}); __m }}",
                            map, key
                        );
                    }
                    return format!(
                        "{{ let mut __m = ({}).clone(); __m.remove(&{}); __m }}",
                        map, key
                    );
                }
            }
            if op == "darcy.math/abs" && args.len() == 1 {
                return format!("({}).abs()", lower!(&args[0]));
            }
            if op == "darcy.math/exp" && args.len() == 1 {
                return format!("({}).exp()", lower!(&args[0]));
            }
            if (op == "darcy.math/min" || op == "darcy.math/max") && args.len() == 2 {
                let a = lower!(&args[0]);
                let b = lower!(&args[1]);
                let meth = if op == "darcy.math/min" { "min" } else { "max" };
                return format!("({}).{}({})", a, meth, b);
            }
            if op == "darcy.math/clamp" && args.len() == 3 {
                let x = lower!(&args[0]);
                let lo = lower!(&args[1]);
                let hi = lower!(&args[2]);
                return format!("({}).clamp({}, {})", x, lo, hi);
            }
            if op == "darcy.core/clone" && args.len() == 1 {
                return format!("({}).clone()", lower!(&args[0]));
            }
            if let Some(sd) = structs.get(op) {
                let rendered: Vec<String> = args.iter().map(|el| lower!(el)).collect();
                let mut parts = Vec::new();
                for (field, expr) in sd.fields.iter().zip(rendered.iter()) {
                    parts.push(format!("{}: {}", field.rust_name, expr));
                }
                return format!("{} {{ {} }}", sd.rust_name, parts.join(", "));
            }
            if let Some((union_name, vdef)) = variants.get(op) {
                let union_rust = type_names
                    .get(union_name)
                    .cloned()
                    .unwrap_or_else(|| rust_type_name(union_name));
                let rendered: Vec<String> = args.iter().map(|el| lower!(el)).collect();
                let mut parts = Vec::new();
                for (field, expr) in vdef.fields.iter().zip(rendered.iter()) {
                    parts.push(format!("{}: {}", field.rust_name, expr));
                }
                return if vdef.fields.is_empty() {
                    format!("{}::{}", union_rust, vdef.rust_name)
                } else {
                    format!(
                        "{}::{} {{ {} }}",
                        union_rust,
                        vdef.rust_name,
                        parts.join(", ")
                    )
                };
            }
            if args.len() == 2
                && [
                    "+",
                    "-",
                    "*",
                    "/",
                    "mod",
                    "=",
                    "<",
                    ">",
                    "<=",
                    ">=",
                    "&",
                    "|",
                    "darcy.op/add",
                    "darcy.op/sub",
                    "darcy.op/mul",
                    "darcy.op/div",
                    "darcy.op/mod",
                    "darcy.op/eq",
                    "darcy.op/lt",
                    "darcy.op/gt",
                    "darcy.op/lte",
                    "darcy.op/gte",
                    "darcy.op/bit-and",
                    "darcy.op/bit-or",
                ]
                .contains(&op.as_str())
            {
                let left_ty = expr_ty(types, &args[0].span());
                let right_ty = expr_ty(types, &args[1].span());
                let bin_op = match op.as_str() {
                    "mod" | "darcy.op/mod" => "%",
                    "=" | "darcy.op/eq" => "==",
                    "darcy.op/add" => "+",
                    "darcy.op/sub" => "-",
                    "darcy.op/mul" => "*",
                    "darcy.op/div" => "/",
                    "darcy.op/lt" => "<",
                    "darcy.op/gt" => ">",
                    "darcy.op/lte" => "<=",
                    "darcy.op/gte" => ">=",
                    "darcy.op/bit-and" => "&",
                    "darcy.op/bit-or" => "|",
                    other => other,
                };
                if let (Some(Ty::Vec(_)), Some(right_ty)) = (left_ty.clone(), right_ty.clone()) {
                    return vec_scalar_binop(
                        bin_op,
                        &args[0],
                        &args[1],
                        casts,
                        types,
                        structs,
                        variants,
                        fn_names,
                        def_names,
                        type_names,
                        fn_env,
                        auto_clones,
                        mutated,
                        true,
                        &right_ty,
                    );
                }
                if let (Some(left_ty), Some(Ty::Vec(_))) = (left_ty.clone(), right_ty.clone()) {
                    return vec_scalar_binop(
                        bin_op,
                        &args[0],
                        &args[1],
                        casts,
                        types,
                        structs,
                        variants,
                        fn_names,
                        def_names,
                        type_names,
                        fn_env,
                        auto_clones,
                        mutated,
                        false,
                        &left_ty,
                    );
                }
                format!("({} {} {})", lower!(&args[0]), bin_op, lower!(&args[1]))
            } else {
                let modes = fn_env
                    .get_arity(op, args.len())
                    .map(|sig| sig.param_modes.clone());
                let rendered: Vec<String> = args
                    .iter()
                    .enumerate()
                    .map(|(idx, el)| {
                        let rendered = lower!(el);
                        let mode = modes
                            .as_ref()
                            .and_then(|m| m.get(idx))
                            .copied()
                            .unwrap_or(ParamMode::ByVal);
                        match mode {
                            ParamMode::ByRef => format!("&{}", rendered),
                            ParamMode::ByRefNoAmp => rendered,
                            ParamMode::ByVal => rendered,
                        }
                    })
                    .collect();
                let name = fn_names
                    .get(&(op.clone(), args.len()))
                    .cloned()
                    .unwrap_or_else(|| rust_value_name(op));
                format!("{}({})", name, rendered.join(", "))
            }
        }
    };

    for ch in casts {
        if spans_eq(&e.span(), &ch.span) {
            inner = format!("({} as {})", inner, ch.target.rust());
            break;
        }
    }
    inner
}

fn spans_eq(a: &Span, b: &Span) -> bool {
    a.start.byte == b.start.byte && a.end.byte == b.end.byte
}

#[derive(Debug)]
enum InterpPart {
    Text(String),
    Expr(String),
}

fn parse_interpolated_string(s: &str) -> Option<Vec<InterpPart>> {
    if !s.contains("${") {
        return None;
    }
    let chars: Vec<char> = s.chars().collect();
    let mut i = 0usize;
    let mut current = String::new();
    let mut parts = Vec::new();
    while i < chars.len() {
        if chars[i] == '$' && i + 1 < chars.len() && chars[i + 1] == '{' {
            if !current.is_empty() {
                parts.push(InterpPart::Text(std::mem::take(&mut current)));
            }
            i += 2;
            let start = i;
            while i < chars.len() && chars[i] != '}' {
                i += 1;
            }
            if i >= chars.len() {
                return None;
            }
            let name: String = chars[start..i]
                .iter()
                .collect::<String>()
                .trim()
                .to_string();
            if name.is_empty()
                || name
                    .chars()
                    .any(|ch| ch.is_whitespace() || ch == '{' || ch == '}')
            {
                return None;
            }
            parts.push(InterpPart::Expr(name));
            i += 1;
            continue;
        }
        current.push(chars[i]);
        i += 1;
    }
    if !current.is_empty() {
        parts.push(InterpPart::Text(current));
    }
    Some(parts)
}

fn escape_format_braces(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '{' => out.push_str("{{"),
            '}' => out.push_str("}}"),
            _ => out.push(ch),
        }
    }
    out
}

fn expr_ty(types: &BTreeMap<SpanKey, Ty>, span: &Span) -> Option<Ty> {
    types.get(&SpanKey::new(span)).cloned()
}

fn lower_index_arg(
    expr: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    fn_names: &FnNameMap,
    def_names: &BTreeMap<String, String>,
    type_names: &BTreeMap<String, String>,
    fn_env: &crate::typecheck::FnEnv,
    auto_clones: &BTreeSet<SpanKey>,
    mutated: &BTreeSet<String>,
) -> String {
    macro_rules! lower {
        ($e:expr) => {
            lower_expr(
                $e,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            )
        };
    }
    let rendered = lower!(expr);
    match expr_ty(types, &expr.span()) {
        Some(Ty::Named(name)) if name == "usize" => rendered,
        _ => format!("darcy_stdlib::rt::cast_usize({})", rendered),
    }
}

fn render_int_literal(v: i64, sp: &Span, types: &BTreeMap<SpanKey, Ty>) -> String {
    match expr_ty(types, sp) {
        Some(Ty::Generic(id)) => format!("darcy_stdlib::rt::from_int::<T{}>({})", id, v),
        Some(Ty::Named(name)) if is_int_type(&name) => format!("{}{}", v, name),
        Some(Ty::Named(name)) if is_uint_type(&name) => format!("{}{}", v, name),
        Some(Ty::Named(name)) if name == "f32" || name == "f64" => format!("{}{}", v, name),
        _ => format!("{}{}", v, "i64"),
    }
}

fn is_int_type(name: &str) -> bool {
    matches!(name, "i8" | "i16" | "i32" | "i64" | "isize")
}

fn is_uint_type(name: &str) -> bool {
    matches!(name, "u8" | "u16" | "u32" | "u64" | "usize")
}

fn vec_scalar_binop(
    op: &str,
    left: &Expr,
    right: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    fn_names: &FnNameMap,
    def_names: &BTreeMap<String, String>,
    type_names: &BTreeMap<String, String>,
    fn_env: &crate::typecheck::FnEnv,
    auto_clones: &BTreeSet<SpanKey>,
    mutated: &BTreeSet<String>,
    vec_on_left: bool,
    scalar_ty: &Ty,
) -> String {
    let vec_expr = if vec_on_left { left } else { right };
    let scalar_expr = if vec_on_left { right } else { left };
    let vec_render = lower_expr(
        vec_expr,
        casts,
        types,
        structs,
        variants,
        fn_names,
        def_names,
        type_names,
        fn_env,
        auto_clones,
        mutated,
    );
    let scalar_render = lower_expr(
        scalar_expr,
        casts,
        types,
        structs,
        variants,
        fn_names,
        def_names,
        type_names,
        fn_env,
        auto_clones,
        mutated,
    );
    let scalar = match scalar_ty {
        Ty::Named(_) => scalar_render,
        _ => scalar_render,
    };
    format!(
        "Arc::new(({}).iter().map(|__x| (*__x) {} {}).collect::<Vec<_>>())",
        vec_render, op, scalar
    )
}

fn lower_for_expr(
    var: &str,
    iter: &crate::ast::Iterable,
    body: &Expr,
    casts: &[crate::typed::CastHint],
    types: &BTreeMap<SpanKey, Ty>,
    structs: &BTreeMap<String, StructDef>,
    variants: &BTreeMap<String, (String, VariantDef)>,
    fn_names: &FnNameMap,
    def_names: &BTreeMap<String, String>,
    type_names: &BTreeMap<String, String>,
    fn_env: &crate::typecheck::FnEnv,
    auto_clones: &BTreeSet<SpanKey>,
    mutated: &BTreeSet<String>,
) -> String {
    match iter {
        crate::ast::Iterable::Range(range) => {
            let start = lower_expr(
                &range.start,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            let end = lower_expr(
                &range.end,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            let ty = expr_ty(types, &range.start.span());
            let step = if let Some(step) = &range.step {
                lower_expr(
                    step,
                    casts,
                    types,
                    structs,
                    variants,
                    fn_names,
                    def_names,
                    type_names,
                    fn_env,
                    auto_clones,
                    mutated,
                )
            } else {
                default_step_for_ty(ty.as_ref(), type_names)
            };
            let cmp = if range.inclusive { "<=" } else { "<" };
            let body_render = lower_expr(
                body,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            format!(
                "{{ let __start = {start}; let __end = {end}; let __step = {step}; let mut {var} = __start; loop {{ if !({var} {cmp} __end) {{ break; }} {body_render}; {var} = {var} + __step; }} }}",
                start = start,
                end = end,
                step = step,
                var = var,
                cmp = cmp,
                body_render = body_render
            )
        }
        crate::ast::Iterable::Expr(ex) => {
            let vec_expr = lower_expr(
                ex,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            let body_render = lower_expr(
                body,
                casts,
                types,
                structs,
                variants,
                fn_names,
                def_names,
                type_names,
                fn_env,
                auto_clones,
                mutated,
            );
            format!(
                "{{ for {} in ({}).iter().cloned() {{ {}; }} }}",
                var, vec_expr, body_render
            )
        }
    }
}

fn default_step_for_ty(ty: Option<&Ty>, type_names: &BTreeMap<String, String>) -> String {
    if let Some(Ty::Named(name)) = ty {
        if is_float_type(name) {
            if name == "f32" {
                return "1.0f32".to_string();
            }
            return "1.0".to_string();
        }
        if is_int_type(name) || is_uint_type(name) {
            return format!("1{}", name);
        }
        if name == "string" {
            return "1".to_string();
        }
        let rust_name = ty_rust(&Ty::Named(name.clone()), type_names);
        return format!("1{}", rust_name);
    }
    "1".to_string()
}

fn is_float_type(name: &str) -> bool {
    matches!(name, "f32" | "f64")
}

fn rust_type_name(name: &str) -> String {
    let mut out = String::new();
    for part in name.split(|c| c == '-' || c == '_') {
        if part.is_empty() {
            continue;
        }
        let mut chars = part.chars();
        if let Some(c) = chars.next() {
            out.push(c.to_ascii_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn ty_rust_infer(ty: &Ty, type_names: &BTreeMap<String, String>) -> String {
    match ty {
        Ty::Generic(_) | Ty::Unknown => "()".to_string(),
        Ty::Vec(inner) => format!("Arc<Vec<{}>>", ty_rust_infer(inner, type_names)),
        Ty::Set(inner) => format!(
            "std::collections::HashSet<{}>",
            ty_rust_infer(inner, type_names)
        ),
        Ty::Option(inner) => format!("Option<{}>", ty_rust_infer(inner, type_names)),
        Ty::Result(ok, err) => format!(
            "Result<{}, {}>",
            ty_rust_infer(ok, type_names),
            ty_rust_infer(err, type_names)
        ),
        Ty::Map(kind, k, v) => {
            let name = match kind {
                MapKind::IMap => "darcy_stdlib::rt::IMap",
                MapKind::Hash => "std::collections::HashMap",
                MapKind::BTree => "std::collections::BTreeMap",
            };
            format!(
                "{}<{}, {}>",
                name,
                ty_rust_infer(k, type_names),
                ty_rust_infer(v, type_names)
            )
        }
        _ => ty_rust(ty, type_names),
    }
}

fn ty_rust(ty: &Ty, type_names: &BTreeMap<String, String>) -> String {
    match ty {
        Ty::Named(s) => {
            if matches!(
                s.as_str(),
                "i8" | "i16"
                    | "i32"
                    | "i64"
                    | "i128"
                    | "u8"
                    | "u16"
                    | "u32"
                    | "u64"
                    | "u128"
                    | "f32"
                    | "f64"
                    | "bool"
                    | "usize"
                    | "isize"
                    | "()"
                    | "string"
                    | "symbol"
            ) {
                if s == "string" {
                    "String".to_string()
                } else if s == "symbol" {
                    "darcy_stdlib::rt::Symbol".to_string()
                } else {
                    s.clone()
                }
            } else {
                type_names
                    .get(s)
                    .cloned()
                    .unwrap_or_else(|| rust_type_name(s))
            }
        }
        Ty::Vec(inner) => format!("Arc<Vec<{}>>", ty_rust(inner, type_names)),
        Ty::Set(inner) => format!("std::collections::HashSet<{}>", ty_rust(inner, type_names)),
        Ty::Option(inner) => format!("Option<{}>", ty_rust(inner, type_names)),
        Ty::Result(ok, err) => format!(
            "Result<{}, {}>",
            ty_rust(ok, type_names),
            ty_rust(err, type_names)
        ),
        Ty::Map(kind, k, v) => {
            let name = match kind {
                MapKind::IMap => "darcy_stdlib::rt::IMap",
                MapKind::Hash => "std::collections::HashMap",
                MapKind::BTree => "std::collections::BTreeMap",
            };
            format!(
                "{}<{}, {}>",
                name,
                ty_rust(k, type_names),
                ty_rust(v, type_names)
            )
        }

        Ty::Generic(id) => format!("T{}", id),
        Ty::Union(items) => {
            let parts: Vec<String> = items.iter().map(|t| ty_rust(t, type_names)).collect();
            // Union represenation in Rust? Assuming enum or just formatting for now if this is for codegen
            // If it's for type string, maybe (A | B)
            // But lower.rs suggests lowering to Rust code?
            // "ty_to_rust_type" suggests generating Rust type name.
            // Rust doesn't have anonymous unions.
            // Maybe it expects a named type or `Box<dyn Any>`?
            // For now, let's use a placeholder or error if it shouldn't happen here.
            // But to fix compilation, I must return String.
            format!("/* Union: {} */ Box<dyn Any>", parts.join(" | "))
        }
        Ty::Unknown => "/* unknown */".to_string(),
    }
}

fn rust_value_name(name: &str) -> String {
    let base = name.rsplit_once('/').map(|(_, tail)| tail).unwrap_or(name);
    let mut out = String::new();
    for c in base.chars() {
        match c {
            'a'..='z' | 'A'..='Z' | '0'..='9' => out.push(c),
            '-' | '_' => out.push('_'),
            '?' => out.push_str("_q"),
            '!' => out.push_str("_bang"),
            '*' => out.push_str("_star"),
            '+' => out.push_str("_plus"),
            '=' => out.push_str("_eq"),
            '<' => out.push_str("_lt"),
            '>' => out.push_str("_gt"),
            '$' => out.push_str("_dollar"),
            '&' => out.push_str("_and"),
            '|' => out.push_str("_or"),
            _ => out.push('_'),
        }
    }
    if out.is_empty() {
        out.push('v');
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}
