(require [darcy.io])
(require [darcy.math])
(require [darcy.op])
(require [darcy.core])
(require [darcy.vec])
(require [darcy.string])
(require [darcy.fmt])
(require [darcy.option])
(require [darcy.result])
(require [darcy.hash-map])
(require [darcy.btree-map])
(require [darcy.rand])
(require [darcy.tensor])
(require [darcy.nn])
(require [darcy.mnist])
(require [darcy.astra.sim])

(defn stdlib-ok [] true)
