use dslc::compile;

#[test]
fn compiles_ok_example() {
    let src = include_str!("../../examples/ok.dsl");
    let out = compile(src).expect("compile ok");
    let expected = "// Generated by dslc compiler for Darcy lang\n#![allow(dead_code)]\n#![allow(unused_parens)]\n#![allow(unused_braces)]\n\n#[derive(Debug, Clone)]\npub struct Order {\n    pub id: Uuid,\n    pub qty: u32,\n    pub price: f64,\n}\n\npub fn total(o: Order) -> f64 {\n    (((o as f64).qty as f64) * o.price)\n}\n\n";
    assert_eq!(out, expected);
}
