use dslc::compile;

#[test]
fn compiles_ok_example() {
    let src = include_str!("../../examples/ok.dsl");
    let out = compile(src).expect("compile ok");
    let expected = "// Generated by dslc compiler for Darcy lang\n#![allow(dead_code)]\n#![allow(unused_parens)]\n#![allow(clippy::redundant_pattern)]\n#![allow(non_shorthand_field_patterns)]\n#![allow(unused_braces)]\n#![allow(unused_imports)]\n#![allow(non_upper_case_globals)]\nuse std::sync::Arc;\n\n\n#[derive(Debug, Clone)]\npub struct Order {\n    pub id: String,\n    pub qty: u32,\n    pub price: f64,\n}\n\nimpl std::fmt::Display for Order {\n    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n        write!(f, \"{:?}\", self)\n    }\n}\n\nfn total(o: &Order) -> f64 {\n    ((o.qty as f64) * o.price)\n}\n\n";
    assert_eq!(out, expected);
}
